### ISSUE TITLE
Using same jemalloc as Rust

### ISSUE THREAD

**Issue by alexreg** [rust-rocksdb/rust-rocksdb#103]
There may now exist an opportunity to use the same jemalloc as Rust, thanks to https://github.com/jemalloc/jemalloc/commit/2319152d9f5d9b33eebc36a50ccf4239f31c1ad9. This is just a heads up. @kaedroho, you may be interested. I haven't checked your custom compilation code yet, but I presume it uses the default system allocator when building, since having two versions of jemalloc creates big problems.

**Comment by arthurprs** [comment]
I looked at the repo but it wasn't clear to me. What does the current HEAD use? Is it the system allocator or another jemalloc?

**Comment by alexreg** [comment]
Honestly, I couldn't figure out either. Maybe @kaedroho could clear this up...

**Comment by iSynaptic** [comment]
Is this still needed? What are the benefits?

**Comment by Kais-DkM** [comment]
According to [rust-lang blog](https://blog.rust-lang.org/2019/01/17/Rust-1.32.0.html#jemalloc-is-removed-by-default), jemalloc was removed from rust in 1.32.0.
For now, I think you can use whatever version of jemalloc you'd like to.

**Comment by iSynaptic** [comment]
Since Rust no longer uses jemalloc by default, it would appear this is no longer needed. Closing and can revisit if needed.
