### ISSUE TITLE
Cannot use snapshot DbIterators across threads

### ISSUE THREAD

**Issue by Damienkatz** [rust-rocksdb/rust-rocksdb#104]
Hit this today, attempting to query database and find matching elements using a snapshot DbIterator on one thread, then use DbIterator from same snapshot on another thread. Because of the lifetime requirements it's not possible.

Potential solution: use std::sync::Arc to hold references to snapshot or inner members. Each DbIterator from a single snapshot will also hold a the same arc references.

**Comment by iSynaptic** [comment]
This is by design. Mutating a `DBIterator` (via `fn next` on the `Iterator` trait) is unsafe from multiple threads. DBIterator is `Send`, so I believe you can put it in an `Arc<Mutex<DBIterator>>` and then use that from multiple threads.
