### ISSUE TITLE
Expose API to restore database from backups

### ISSUE THREAD

**Issue by benoitc** [rust-rocksdb/rust-rocksdb#135]
the backup module can backup and has restore options, but how do we backup?

**Comment by iSynaptic** [comment]
Can you provide more detail? What are you trying to do?

**Comment by rohitjoshi** [comment]
How do I restore from an existing backup directory?  I don't see `pub unsafe extern "C" fn rocksdb_backup_engine_restore_db_from_latest_backup()` is made available in the Rust interface.

**Comment by iSynaptic** [comment]
I can see that the library doesn't expose the ability to restore an backup. Looks like the work has been started but not finished.  I've labeled this as a bug. Anyone is free to take on fixing this, otherwise I will plan on it once other in-flight work is completed.

**Comment by rohitjoshi** [comment]
I have implemented this on my local branch. I will submit a PR.

**Comment by iSynaptic** [comment]
Looks like this will be addressed in #249 by @rohitjoshi.

**Comment by rohitjoshi** [comment]
@iSynaptic I am close #249 and splitting into two different PRs.
Submitted #272 for this issue.

**Comment by iSynaptic** [comment]
Fixed by #272.
