### ISSUE TITLE
investigate speeding up builds by short-circuiting librocksdb-sys c++ compilation when unchanged

### ISSUE THREAD

**Issue by spacejam** [rust-rocksdb/rust-rocksdb#137]

**Comment by rrichardson** [comment]
This is a good idea,  until then, people might experience a much nicer build experience after https://github.com/alexcrichton/cc-rs/pull/261

**Comment by iSynaptic** [comment]
Is this still an open issue, or was it solved by alexcrichton/cc-rs#261?

**Comment by iSynaptic** [comment]
@rrichardson I don't experience a rebuild of `librocksdb-sys` every time - only the initial build for a given `Cargo.toml`.  Can you share an example of where/how this is happening?

**Comment by iSynaptic** [comment]
Not sure how to move this forward and this issue has been fairly inactive for some time. I'm going to close. We can always revisit if needed...
