### ISSUE TITLE
Link error on Windows

### ISSUE THREAD

**Issue by PiedmontStream** [rust-rocksdb/rust-rocksdb#164]
rocksdb link error.
add `port/win/win_thread.cc` into the file `rust-rocksdb/librocksdb-sys/rocksdb_lib_sources.txt` can fix it.
the methods of `rocksdb::port::WindowsThread` were lost on windows.

**Comment by gagarin55** [comment]
@spacejam Could you please apply this fix and release new version of librocksdb-sys crate

**Comment by iSynaptic** [comment]
This should be closed.
