### ISSUE TITLE
Base documentation

### ISSUE THREAD

**Issue by guidiego** [rust-rocksdb/rust-rocksdb#172]
I'm a beginner in rust, I think that is a good ideia add a basic documentation of how use the API of `rust-rocksdb` <3

Thx u guys!

**Comment by iSynaptic** [comment]
The best source for the documentation will either be [the doc.rs site](https://docs.rs/rocksdb) generated from Rust comments or the [official RocksDB documentation](https://github.com/facebook/rocksdb/wiki), which we try to make applicable to this library as much as we can.

If you have some areas of documentation that need improvement, please let us know.  I think the general approach to documentation has been to improve the generated doc site rather then create a separate documentation site.
