### ISSUE TITLE
Why are DbRawIterator::key_inner and DbRawIterator::value_inner unsafe?

### ISSUE THREAD

**Issue by sfackler** [rust-rocksdb/rust-rocksdb#173]
Their documentation just mentions not reusing the buffer after moving the cursor, but the compiler will prevent that since the return value borrows the iterator.

**Comment by iSynaptic** [comment]
This is unsafe because the iterator may still be alive, but the pointers returned by `key_inner` and `value_inner` is only valid until the cursor moves. Once it does, dereferencing those pointers is unsafe and cannot be prevented by lifetimes.
