### ISSUE TITLE
Missing `ReadOptions.readahead_size`

### ISSUE THREAD

**Issue by cswinter** [rust-rocksdb/rust-rocksdb#203]
I like to "tune" my RocksDB instances by changing random settings that end up having no impact on performance whatsoever. `ReadOptions.readahead_size` will be the one though so it would be great to have.

**Comment by cswinter** [comment]
Actually, is there any way at all to pass `ReadOptions` when creating an iterator? All the methods I've been able to find seem to be private.

**Comment by iSynaptic** [comment]
#253 adds the ability to provide `ReadOptions` when creating an iterator.  I'll work on exposing more of the `ReadOptions` options.

**Comment by iSynaptic** [comment]
#260 is a broader issue that encompasses this issue.
