### ISSUE TITLE
While installing Rustic Search 

### ISSUE THREAD

**Issue by dineshmickey** [rust-rocksdb/rust-rocksdb#206]
Im getting the Following Error 

  Compiling librocksdb-sys v5.11.3
error: failed to run custom build command for `librocksdb-sys v5.11.3`
process didn't exit successfully: `/home/rusticsearch/target/debug/build/librocksdb-sys-48ca55f7970a0b0f/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.*\', \'libclang-*.so\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by iSynaptic** [comment]
Can you provide some more information? What OS? What version of Rust? Is clang installed?

**Comment by iSynaptic** [comment]
Closing because this issue has gone stale. Can reopen if needed later.

**Comment by jonathanstrong** [comment]
just encountered this as well trying to build LocustDB. ubuntu 16.04, rustc v1.33.0-nightly 2019-1-21. gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609. 

```console
error: failed to run custom build command for `librocksdb-sys v5.14.2`
process didn't exit successfully: `/home/username/src/LocustDB/target/release/build/librocksdb-sys-c0c633e0959a6382/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.*\', \'libclang-*.so\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Interestingly, same thing happened to me recently with the zstd crate, which was subsequently fixed somehow, but I don't know what they did. Here's the [issue](https://github.com/gyscos/zstd-rs/issues/51).

Not sure what is driving this, but it's not unique to this crate.

**Comment by iSynaptic** [comment]
Do you have clang installed?  `apt list --installed 2>/dev/null | grep clang`
If not, try installing that: https://blog.kowalczyk.info/article/k/how-to-install-latest-clang-6.0-on-ubuntu-16.04-xenial-wsl.html

**Comment by jonathanstrong** [comment]
actually I had just worked around it that way ... but why gcc didn't work is still mysterious, right?
