### ISSUE TITLE
Open DB in read-only mode

### ISSUE THREAD

**Issue by eupn** [rust-rocksdb/rust-rocksdb#213]
It would be nice to add possibility to open DB in read-only mode, eg. at least for:

* Reading DB from multiple processes
* Create checkpoints of DB which is currently used by other process

This is supported by RocksDB, the only thing needed is to add FFI bindings and `open_readonly` method to `DB` structure.

**Comment by iSynaptic** [comment]
@eupn I've just pushed the beginnings of `ReadOnlyDB` into #268.  Right now all it supports is `get_*` operations, but it will soon support the other read operations.

**Comment by iSynaptic** [comment]
@eupn [Here](https://github.com/rust-rocksdb/rust-rocksdb/blob/31657c6ac593cc49267c23d4bbe51c0f462bf3ee/tests/test_read_only_db.rs) is one of the first tests for `ReadOnlyDB`.

**Comment by ansjsun** [comment]
@iSynaptic  I can not found `ReadOnlyDB` in master branch .

**Comment by m1sterc001guy** [comment]
Is there any update on this? It looks like subu-cliqz closed the issue when they merged a patch into a private branch, not the upstream branch. Does rust rocksdb support multiple processes reading from the same db (one in read-only mode) or is that not currently supported?

**Comment by zdila** [comment]
Any update on this?

**Comment by zdila** [comment]
Actually it seems to be already implemented:
```rs
DB::open_for_read_only(...)
```
