### ISSUE TITLE
Travis CI is not working

### ISSUE THREAD

**Issue by iSynaptic** [rust-rocksdb/rust-rocksdb#214]
This repo's CI build via Travis CI is configured using the, [now deprecated](https://developer.github.com/changes/2018-04-25-github-services-deprecation), GitHub Services and will cease to function on January 31, 2019. There appears to be [a migration solution](https://docs.travis-ci.com/user/legacy-services-to-github-apps-migration-guide/).

**Comment by iSynaptic** [comment]
The existing CI build is configured under @spacejam's Travis CI account.  I'm not sure if that can use that in-place, be migrated to a `rust-rocksdb` Travis CI organization account, or if we need to stand up a new one. Suggestions?

**Comment by iSynaptic** [comment]
Additionally, it doesn't look like CI builds are happening for PRs anymore. The [last one to run](https://travis-ci.org/spacejam/rust-rocksdb/pull_requests) was two months ago, even though there have been more recent PRs submitted.

**Comment by aleksuss** [comment]
@iSynaptic I've just created a new PR and have recognized that with Travis CI everything is OK. I don't see an issue.

**Comment by spacejam** [comment]
I enabled travis for the rust-rocksdb org, and I think it may be working now. Thanks for updating the link, @aleksuss !

**Comment by iSynaptic** [comment]
Agreed. It appears to be working now. Closing...
