### ISSUE TITLE
Add web chat collaboration

### ISSUE THREAD

**Issue by iSynaptic** [rust-rocksdb/rust-rocksdb#215]
@aleksuss @vitvakatu I was thinking it might be useful to add a link to web chat room, like [Gittter](https://gitter.im) for this repo. Thoughts?

**Comment by aleksuss** [comment]
@iSynaptic i guess it's a good idea.

**Comment by spacejam** [comment]
approved gitter API request

**Comment by iSynaptic** [comment]
@spacejam Can you setup the maintainers as admins to the org? [I've been told](https://gitter.im/gitterHQ/gitter?at=5bed9b209600d10e64b50fe3) we need to setup Gitter IM for the org in order to get it setup for the repo.

**Comment by spacejam** [comment]
@iSynaptic oops! sorry for that. I've enabled gitter for rust-rocksdb, and configured all org-level members as admins. This means that each our @rust-rocksdb/crate-publishers may now additionally create new repos and add contributors to them.
