### ISSUE TITLE
Upgrade to the latest RocksDB core library

### ISSUE THREAD

**Issue by iSynaptic** [rust-rocksdb/rust-rocksdb#217]
The rust binding is currently targeting version `5.14.2` of the core library, but `5.15.10` was released a little over a month ago. We should upgrade to the latest version, assuming it doesn't result in any breaking/surprising changes (version 5.15.0 introduced [API changes and new features](https://github.com/facebook/rocksdb/releases/tag/v5.15.10)).

**Comment by elichai** [comment]
I don't know a lot about autogenerated bindings, but is it possible to maybe move something like a dynamic linking?
For example, in the leveldb bindings ( https://github.com/skade/leveldb-sys ) you need to install `libleveldb-dev` from the distribution repository and then it doesn't need to compile the whole thing every time, so it compiles only the bindings which takes a few seconds.

Here only compiling librocksdb-sys can take a few minutes, because (I assume) it compiles the C++ code of rocksdb.

**Comment by aleksuss** [comment]
@elichai good point. I thought about this too and I'm planning to do this in the future.

**Comment by iSynaptic** [comment]
I guess I'm torn on this. I like the convenience of statically linking the library and not needing additional dependencies installed.  Cache prevents the need to constantly recompile the library, so I'm not bothered by needing to compile the whole thing once. Given that it's been statically included for so long, I'd want to get the communities' thoughts on the matter, perhaps in a different issue.

**Comment by vitvakatu** [comment]
I'd like to allow both static and dynamic linkage (probably by using features) - this would be the most flexible approach as for me. Compile time is not an issue right now for the library itself, but it also affects compile time of other projects which depend on us, which is unfortunate.

**Comment by iSynaptic** [comment]
@vitvakatu I like that idea (supporting both).

**Comment by iSynaptic** [comment]
Does #166 achieve this already?  Perhaps for both static and dynamic linking is already supported but just not well documented or ergonomic?

**Comment by iSynaptic** [comment]
I'm going to assume #166 achieves the dynamic linkage requirement unless someone says otherwise.  The current version of RocksDB as of today is [5.17.2](https://github.com/facebook/rocksdb/releases) and is getting close to 4 months old. I'll make a pass at updating to the latest version.

**Comment by iSynaptic** [comment]
Fixed in #261. Thanks @aleksuss!

**Comment by elichai** [comment]
Just to clarify, If I want dynamic linking I should add the env var `ROCKSDB_LIB_DIR` with the location of the `.so`/`.a` in it, right?

**Comment by aleksuss** [comment]
@elichai yes
