### ISSUE TITLE
Transition to Rust 2018

### ISSUE THREAD

**Issue by iSynaptic** [rust-rocksdb/rust-rocksdb#224]
Rust 2018 is [slated to land in December 2018](https://blog.rust-lang.org/2018/07/27/what-is-rust-2018.html). Perhaps we should transition to it?  Thoughts?

**Comment by vitvakatu** [comment]
I propose to wait just a bit, to avoid some unpredictable bugs and regressions and make sure that the whole ecosystem will make a transition together with us. (one of the examples - `failure` wasn't ready to `dyn Trait` syntax and caused a lot of problems in various projects which depend on it)

**Comment by iSynaptic** [comment]
@vitvakatu Sounds good. I'll leave this open as a reminder to reconsider after some time has passed.

**Comment by iSynaptic** [comment]
@vitvakatu @aleksuss There have been 2 releases since Rust 2018 landed in December. Any objections to moving over to it?

**Comment by vitvakatu** [comment]
No objections from me,  Rust 2018 looks stable enough now
