### ISSUE TITLE
Invalid pointers to underlying objects outlive DB

### ISSUE THREAD

**Issue by iSynaptic** [rust-rocksdb/rust-rocksdb#235]
This is related to #234.

Pointers to underlying RocksDB objects (eg. iterators) can outlive the underlying `DB` object. If these objects are used after the `DB` is `Drop`-ped and closed, this can cause segfaults. Consider the implications to adding lifetime annotations to structs that manage these underlying objects.

**Comment by aleksuss** [comment]
Very interesting. Could you please express an example of code that illustrates that bug ?

**Comment by iSynaptic** [comment]
@aleksuss Yes, I will (assigned this issue to myself). #234 has one example, but I suspect there are others.  I'll try to find as many as I can.

**Comment by iSynaptic** [comment]
Also, thanks to @rob-solana for finding this issue via #234 .

**Comment by iSynaptic** [comment]
I have a branch that fixes this issue. Should be a PR soon.

**Comment by iSynaptic** [comment]
Fixed by #253
