### ISSUE TITLE
WriteBatch::clear

### ISSUE THREAD

**Issue by gim913** [rust-rocksdb/rust-rocksdb#239]
Hi,

is there a reason not to have [WriteBatch::clear()](https://github.com/facebook/rocksdb/blob/64324e329eb0a9b4e77241a425a1615ff524c7f1/db/write_batch.cc#L205)? + [.h](https://github.com/facebook/rocksdb/blob/64324e329eb0a9b4e77241a425a1615ff524c7f1/include/rocksdb/write_batch.h#L154) (maybe there's some idiom i'm not aware of)

**Comment by aleksuss** [comment]
@gim913 hello. I suppose it's just because a rare usage of this functional. But I guess it's nice to have 👍🏻

**Comment by aleksuss** [comment]
There was added #240
