### ISSUE TITLE
Get document tests to run as part of the CI build

### ISSUE THREAD

**Issue by iSynaptic** [rust-rocksdb/rust-rocksdb#257]
See this explanation: https://doc.rust-lang.org/rustdoc/documentation-tests.html

**Comment by ekmartin** [comment]
Pretty sure they're run as a part of `cargo test`?

https://travis-ci.org/rust-rocksdb/rust-rocksdb/jobs/488739048#L1118

**Comment by iSynaptic** [comment]
I've seen them not run in the past, but perhaps they've been fixed...closing.
