### ISSUE TITLE
Documentation: What is the standard procedure for sharing DB across threads?

### ISSUE THREAD

**Issue by hlb8122** [rust-rocksdb/rust-rocksdb#269]
Suppose 

`let db = DB::open_default("path/for/rocksdb/storage").unwrap();`

I want to share this between threads and allow them to get and put independently.

It is not clear whether I should wrap `db` as `Arc::new(db)` or go the whole hog and wrap it in a mutex too (`Arc::new(Mutex::new(db))`)?

**Comment by iSynaptic** [comment]
`DB` is both `Send` and `Sync`, so the only thing you will need to wrap it with is `Arc` so it will be correctly `Drop`ed.  All the thread safety is provided by the underlying RocksDB library.
