### ISSUE TITLE
Lazy init static and how to drop/close gracefully?

### ISSUE THREAD

**Issue by nlfiedler** [rust-rocksdb/rust-rocksdb#270]
I'm writing a long-lived application that will use RocksDB, and for convenience I want to keep the database reference and functions in a single module. To that end, I want to use `lazy_static` to initialize the DB reference, and the db-related functions deref that and operate on the database. Eventually the program will exit, so how can I ensure the database has been properly flushed and closed? There is no `close()` function on `DB`, and I cannot `drop` a static (e.g. during `atexit`). Should I be opening and closing the database with every function call? Do I keep a single `db` reference in `main` and pass it everywhere that it will be needed? Thanks for your guidance.

**Comment by iSynaptic** [comment]
I'm not entirely sure how to advise you, but I'll do my best.  The only way to close a `DB` is to implicitly or explicitly have it `Drop`ped.  I'm not sure how `lazy_static` works, but if you can confirm that as part of it's internal implementation it properly drops the `DB`, you shouldn't need to explicitly call `drop`.

An alternative, as you mentioned, would be to create the `DB` at the beginning of the `main` function and then pass references around. When the program terminates, the `DB` will be `Drop`ped and the underlying database will be closed.

Unless you are calling operations *very* infrequently (measured in minutes), I would recommend you not open and close the `DB`.  You will suffer performance issues and likely the library will complain about not being able to acquire the `LOCK` file unless you are very careful to only have one `DB` in existence at any one moment.

**Comment by vitvakatu** [comment]
`lazy_static` will not call Drop on exit, because it works with the plain old statics, nothing magical.

**Comment by iSynaptic** [comment]
In that case, I would recommend not using `lazy_static` with `DB` -- rather I would suggest you create the `DB` in the `main` function and pass around references.

**Comment by nlfiedler** [comment]
I tried in vain to use `Mutex` and `Option` with `atexit` so I could `take` the value, but that resulted in a segfault (while running the tests). Instead I'll open the database at the appropriate time, do a bunch of operations, and then let it drop naturally. That fits the workflow of the application just fine. For testing, I'll use integration tests and `lazy_static` to avoid opening the database for every test function. I'm not concerned about properly closing the database for the tests.

Thanks for your help.
