### ISSUE TITLE
Parallel writing

### ISSUE THREAD

**Issue by pakipaki2000** [rust-rocksdb/rust-rocksdb#271]
Hi,

I don't find how to use the native RocksDB functions to do parallel writing/reading.

Thanks guys :)

**Comment by iSynaptic** [comment]
For the most part, the [underlying RocksDB library](https://rocksdb.org/) takes care of making sure all parallel reading and writing is done safely.  I recommend you take a look at the [official documentation](https://github.com/facebook/rocksdb/wiki) if you have specific questions about specific read/write operations.

This wrapper library tries its best to make use of Rust's type system to prevent using that library in an unsafe way. So, if you are having difficulty using `DB` or one of the other types from multiple threads, I would recommend looking at some of the smart pointer types in Rust, such as `Rc`, `Arc`, `Mutex`, and so on. 

The official Rust documentation will do a much better job than I can in properly explaining how to use those to manage the [lifecycle ](https://doc.rust-lang.org/book/ch15-00-smart-pointers.html) and [thread safety](https://doc.rust-lang.org/book/ch16-00-concurrency.html) when executing operations against the `DB`.  

Beyond this, without more details from you, I don't know how I can be of assistance.  If this information doesn't help address your issue, please open another issue and be more specific of the problem that you are facing, preferably with a code sample.
