### ISSUE TITLE
Is a new release upcoming?

### ISSUE THREAD

**Issue by elichai** [rust-rocksdb/rust-rocksdb#273]
Hi,
Just wanted to ask if there's an ETA for the next release so I could stop using the old fork(https://github.com/elichai/rust-rocksdb/) that let's me pass ReadOptions for the DBIterator :)

**Comment by iSynaptic** [comment]
I don't think we've got a specific date picked for the next release. We've got a few PRs in flight - I suspect once they are merged we'll have a release.

**Comment by elichai** [comment]
Thanks!

**Comment by iSynaptic** [comment]
@elichai I just release 0.12.0, which should have the changes you are looking for. Let us know if it works out for you.

**Comment by elichai** [comment]
@iSynaptic I just looked at it and I see that `DB` has a `iterator_opt()` function but only Snapshot has a `iterator_cf_opt()`, am I missing something or making a cf iterator with options is missing?
If so I can make a PR for it quickly.

Thanks.

**Comment by iSynaptic** [comment]
@elichai I think you are right. Feel free to submit a PR. Otherwise, it will be addressed by #268.
