### ISSUE TITLE
Getting "warning: redundant linker flag specified for library `c++` " on macOS10.14

### ISSUE THREAD

**Issue by xuchaoqian** [rust-rocksdb/rust-rocksdb#274]
Similar to this issure: https://github.com/rust-rocksdb/rust-rocksdb/issues/210
The compiling command as following: 

 Running `rustc --crate-name librocksdb_sys /Users/abc/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-5.14.3/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="bzip2"' --cfg 'feature="default"' --cfg 'feature="lz4"' --cfg 'feature="snappy"' --cfg 'feature="static"' --cfg 'feature="zlib"' --cfg 'feature="zstd"' -C metadata=e616a35700f2be23 -C extra-filename=-e616a35700f2be23 --out-dir /Users/abc/codebase/hongjia/indicators-server/target/debug/deps -L dependency=/Users/abc/codebase/hongjia/indicators-server/target/debug/deps --extern libc=/Users/PATCH/codebase/hongjia/indicators-server/target/debug/deps/liblibc-0d918c6e82cf8f8b.rlib --cap-lints allow -L native=/Users/abc/codebase/hongjia/indicators-server/target/debug/build/librocksdb-sys-860d07970a8bb6ff/out -L native=/Users/abc/codebase/hongjia/indicators-server/target/debug/build/librocksdb-sys-860d07970a8bb6ff/out -L native=/Users/abc/codebase/hongjia/indicators-server/target/debug/build/librocksdb-sys-860d07970a8bb6ff/out -L native=/Users/abc/codebase/hongjia/indicators-server/target/debug/build/librocksdb-sys-860d07970a8bb6ff/out -L native=/Users/abc/codebase/hongjia/indicators-server/target/debug/build/librocksdb-sys-860d07970a8bb6ff/out -L native=/Users/abc/codebase/hongjia/indicators-server/target/debug/build/librocksdb-sys-860d07970a8bb6ff/out -l static=rocksdb -l c++ -l static=snappy -l c++ -l static=lz4 -l static=zstd -l static=z -l static=bz2`

**Comment by iSynaptic** [comment]
I don't think we can do anything to address this since it's from an upstream library. We recently suppressed some of the warnings in #245. Not ideal, but it should address the issue in the next release.
