### ISSUE TITLE
Lacking options (mmap)

### ISSUE THREAD

**Issue by pakipaki2000** [rust-rocksdb/rust-rocksdb#283]
Hi,

Apparently those options aren't working in this crate.
options.allow_mmap_reads and options.allow_mmap_writes

Thanks :)

**Comment by HandleMaser** [comment]
Having the same issue, Rust RocksDB is slow because of it :(

**Comment by aleksuss** [comment]
Added in this PR #285

**Comment by pakipaki2000** [comment]
Awesome! Thanks aleksuss

**Comment by iSynaptic** [comment]
#285 has been merged to master.

**Comment by pakipaki2000** [comment]
Hi,

When will this be available in the crates.io?

Thank you
