### ISSUE TITLE
error: failed to run custom build command for `librocksdb-sys v5.17.2`

### ISSUE THREAD

**Issue by freehere107** [rust-rocksdb/rust-rocksdb#286]
## mac version

mac mojave 10.14.3

## Got error
error: failed to run custom build command for `librocksdb-sys v5.17.2`
process didn't exit successfully: `/gotham-city/gotham-server/target/debug/build/librocksdb-sys-531f568e71a25329/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/

--- stderr
libclang: crash detected during parsing: {
  'source_filename' : ''
  'command_line_args' : ['--target=x86_64-apple-darwin', '-isystem', '/usr/local/include', '-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include', '-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include', '-isystem', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include', '-isystem', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks', 'rocksdb/include/rocksdb/c.h'],
  'unsaved_files' : [],
  'options' : 1,
}
thread 'main' panicked at 'libclang error; possible causes include:
- Invalid flag syntax
- Unrecognized flags
- Invalid flag arguments
- File I/O errors
If you encounter an error missing from this list, please file an issue or a PR!', src/libcore/option.rs:1034:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

## my clang version

Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

## rust version
rustc 1.33.0 (2aa4c46cf 2019-02-28)

## cargo version
cargo 1.33.0 (f099fe94b 2019-02-12)

**Comment by freehere107** [comment]
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:312
   7: core::char::methods::<impl char>::escape_debug
             at src/libcore/panicking.rs:85
   8: core::char::methods::<impl char>::escape_debug
             at src/libcore/option.rs:1038
   9: <bindgen::CodegenConfig as bindgen::CodegenConfig::all::__BitFlags>::DESTRUCTORS
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/option.rs:312
  10: bindgen::ir::context::BindgenContext::new
             at /Users/sunbobin/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.47.3/src/ir/context.rs:562
  11: bindgen::Bindings::generate
             at /Users/sunbobin/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.47.3/src/lib.rs:1778
  12: bindgen::args_are_cpp::{{closure}}
             at /Users/sunbobin/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.47.3/src/lib.rs:1186
  13: build_script_build::bindgen_rocksdb
             at librocksdb-sys/build.rs:34
  14: build_script_build::main
             at librocksdb-sys/build.rs:290
  15: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  16: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  17: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:92
  18: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  19: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  20: build_script_build::main

**Comment by iSynaptic** [comment]
Does compiling any Rust project work with Clang 10.0 on your system?

**Comment by freehere107** [comment]
@iSynaptic yes,i compiling https://github.com/KZen-networks/gotham-city/tree/master/gotham-client
,that ok,but only compiling librocksdb-sys fail

**Comment by iSynaptic** [comment]
@freehere107 Strange. We've got [a CI build](https://travis-ci.org/rust-rocksdb/rust-rocksdb) that ensures it compiles on Mac OS. I'm wondering if there is some tooling version incompatibilities causing this.  I don't have access to a Mac - is it possible for you to try an earlier version of Clang to see if that is where the incompatibility is coming from?

**Comment by freehere107** [comment]
@iSynaptic ok. i try it, thank you

**Comment by iSynaptic** [comment]
@freehere107 Did a different version of Clang work?

**Comment by freehere107** [comment]
@iSynaptic Still have same error.i reopen this issue

**Comment by iSynaptic** [comment]
@aleksuss I'm not using a Mac for my workstation, are you?  If so, are you able to reproduce this?

**Comment by vitvakatu** [comment]
Cannot reproduce. The exact same Mac version, clang and rustc versions

**Comment by iSynaptic** [comment]
@vitvakatu Thanks!

@freehere107 Our Mac CI build and @vitvakatu's Mac cannot reproduce. I'm going to close for now, but if you can pinpoint what might be causing the error for you, please post the details here.

**Comment by aleksuss** [comment]
@iSynaptic I can't reproduce it as well 😕

**Comment by freehere107** [comment]
I try reinstall llvm, it solved, `brew upgrade llvm`
