### ISSUE TITLE
Crates version bump?

### ISSUE THREAD

**Issue by valeriansaliou** [rust-rocksdb/rust-rocksdb#293]
Hello there,

I'm using RocksDB, and `rust-rocksdb` for a project of mine, Sonic: https://github.com/valeriansaliou/sonic (it's getting popular!)

I've recently sent a PR that was accepted: #290 ; which contents were required for Sonic's use of RocksDB.

As to be able to push the updated Sonic version to Crates.io, I'd need Sonic's updated `rust-rocksdb` dependency to be sourced from Crates, and not Git (which is what I'm currently doing). Crates.io just refuses to accept packages w/ Git dependencies to be pushed to the repository.

Would it be possible to bump `rust-rocksdb` version soon? Some people are waiting for the latest Sonic release to be published to Crates, and I need to tell them to wait due to `rust-rocksdb` 😉 

Cheers!

**Comment by iSynaptic** [comment]
@alexreg @vitvakatu Okay with a 0.12.2 release?

**Comment by valeriansaliou** [comment]
Sorry to bother with that, but would it be possible to fast-track this? I'm waiting for the `rust-rocksdb` updated version to be published on Crates in order to be able to publish a new Sonic version.

**Comment by iSynaptic** [comment]
My apologies for the slow response on this one. Been busy relocating to another city and have had limited time/internet access for a while.  Just published 0.12.2 which should have your updates.

**Comment by valeriansaliou** [comment]
Perfect, thanks a ton! Bumping Sonic now on Crates 👍
