### ISSUE TITLE
Dangling pointers with set_iterate_upper_bound

### ISSUE THREAD

**Issue by rnarubin** [rust-rocksdb/rust-rocksdb#299]
I've run into an issue when using the `set_iterate_upper_bound` method on `ReadOptions` when passed to an iterator.
The C bindings store a pointer to the given key using a `Slice` struct owned by `rocksdb_readoptions_t`. The iterator in turn stores a pointer to this `Slice`, which is accessed with every iteration to check whether the upper bound has been reached. As a consequence, both the key and the ReadOptions struct must live at least as long as the iterator, or else they leave dangling pointers (I ran into this segfault).
This is a similar problem to #253 where applying a lifetime to ReadOptions and the key passed to `set_iterate_upper_bound` could statically enforce the requirement that they aren't dropped before the iterator is.
However such a lifetime change has some far-reaching consequences because much of the library code today constructs ReadOptions just long enough to instantiate the iterator, and drops it thereafter (the user doesn't have to provide or own options themselves). The lifetime restriction is only relevant when the upper bound is set, so these uses are still sound, and requiring that all iterator operations provide a long-lived ReadOptions is onerous.

I'm not sure what the best solution is. From a safety perspective, I think it's either to enforce these lifetimes and require user code to own their ReadOptions, or possibly to take ReadOptions by value and store them within the `DBRawIterator` struct so that they always live long enough.
Alternatively, the `set_iterate_upper_bound` method could be labelled `unsafe` and have some documentation explaining the requirements, because it's the only pointer stored in ReadOptions (there's also an iterate_lower_bound Slice which would suffer from the same problem, but this function is not present in the Rust API yet).

**Comment by hjiayz** [comment]
https://github.com/hjiayz/rust-rocksdb/blob/7ba1f9d64abdc96c81b1415eb1685470f96e2eac/src/db_options.rs#L83
