### ISSUE TITLE
clang-sys, not latest version

### ISSUE THREAD

**Issue by pakipaki2000** [rust-rocksdb/rust-rocksdb#303]
error: failed to select a version for `clang-sys`.
    ... required by package `bindgen v0.47.0`
    ... which is depended on by `librocksdb-sys v5.18.3`
    ... which is depended on by `rocksdb v0.12.2`
versions that meet the requirements `^0.27.0` are: 0.27.0

current clang-sys: 0.28

Apparently you don't use the last version of Bindgen (0.49.0) and probably clang-sys.
I think it require an immediate update :)

**Comment by jensim** [comment]
`clang-sys` now has 1.0.0 version

**Comment by stanislav-tkach** [comment]
Closed by #460.
