### ISSUE TITLE
Q: How to access the sequence number of an entry?

### ISSUE THREAD

**Issue by nlfiedler** [rust-rocksdb/rust-rocksdb#325]
Seems like RocksDB tags every entry with a monotonically increasing sequence number, and there might be some means of accessing that. In fact, it looks like getting a snapshot should return the current sequence number. Is this exposed somewhere in rust-rocksb and I just can't find it? Thanks for your help.

**Comment by vitvakatu** [comment]
Does the RocksDB itself exposes this functionality? `rust-rocksdb` is just a binding and will not expose anything that is unavailable in a parent library.

**Comment by nlfiedler** [comment]
Sorry, I should have looked for a reference sooner. Admittedly I'm not that good at reading large C code bases any more, but it looks like there are a couple of functions related to sequence numbers. There's `GetLatestSequenceNumber()` in `include/rocksdb/db.h` and another function named `rocksdb_get_latest_sequence_number()` in `db/c.cc` that invokes it. There are also numerous tests invoking `GetLatestSequenceNumber()` so maybe that's the public function? Again, not too good at reading large C code bases in short order.

**Comment by vitvakatu** [comment]
Thank you for a little investigation. This function is indeed exists in a public API (and Java bindings exports it as well). It would be fairly easy to add. If you want, you can send a PR (or I can do it myself).

**Comment by nlfiedler** [comment]
You're much better off not letting me touch the code. :)

**Comment by nlfiedler** [comment]
Fantastic, thank you. The reason I asked about the sequence number is that I want to implement a secondary index in RocksDB, and the sequence number is a very good way to detect stale index records. The project is here, https://github.com/nlfiedler/mokuroku -- still needs a lot of work though.
