### ISSUE TITLE
Wrap the GetUpdatesSince() function

### ISSUE THREAD

**Issue by nlfiedler** [rust-rocksdb/rust-rocksdb#331]
This function relies on the sequence number feature of RocksDB, and returns an iterator that yields every update made since that particular sequence. Since I saw how to add a function to rust-rocksdb earlier, I may submit a PR for this when the time comes (I'm not in a rush, just wanted to get this filed for now). Thanks for bringing RocksDB to Rust, it's been awesome.

**Comment by vitvakatu** [comment]
Great, feel free to submit a PR!

**Comment by nlfiedler** [comment]
Tried looking at how this could be added. The function in question takes a new kind of options (`rocksdb_wal_readoptions_t`) and returns a new kind of iterator (`rocksdb_wal_iterator_t`). From what I can tell, the options have no implementation of any sort, and are optional given the implementation of `rocksdb_get_updates_since()`. The iterator does not appear to have a factory function, and its API is so different I can't even tell how to get the keys and values from it.

**Comment by vitvakatu** [comment]
You probably should look at the version 6.1.2 of the rocksb, cause we have a PR that will probably be merged soon (#328). By the way, this PR compiles on Linux and Mac, so you can try it yourself to look through generated code.

You can use `cargo doc --open` to get a full list of functions and types generated by the binding in `librocksdb-sys` crate. You can also open a file `target/debug/build/librocksdb-sys-*/out/bindings.rs` to read through generated code.

Regarding `GetUpdatesSince`: looks like in 6.1.2 read_options contains only a single boolean: https://github.com/facebook/rocksdb/blob/2b38e2dd6602a17a2010308580fd5d8c91dea650/include/rocksdb/transaction_log.h#L113

A returned iterator can be used with a functions listed in the same file: https://github.com/facebook/rocksdb/blob/2b38e2dd6602a17a2010308580fd5d8c91dea650/include/rocksdb/transaction_log.h

To get values from it you need to call GetBatch() (called `rocksdb_wal_iter_get_batch` in bindings).

**Comment by vitvakatu** [comment]
Perhaps you can create an issue in facebook/rocksdb repo and ask how to solve your problem in a ideomatic way?

**Comment by nlfiedler** [comment]
First, thank you for being patient with me. I've finally understood how to get the underlying data: call `GetUpdatesSince()`, then for each iteration get the writebatch, and then iterate over the writebatch itself. However, it is not a normal iterator. From what I can tell, this will be the first time that callbacks are used in the Rust bindings, as the writebatch_iterate invokes application callbacks for each put and delete operation in the batch. In any case, I now have something to work toward, so I'll go away and be quiet for a while. Thanks again.

**Comment by vitvakatu** [comment]
I don't know the whole rust-rocksdb codebase yet, but maybe [SliceTransform](https://docs.rs/rocksdb/0.12.3/rocksdb/struct.SliceTransform.html) would give you some examples of dealing with callbacks. Don't hezitate to ask in case of troubles!

**Comment by nlfiedler** [comment]
I'm stuck with how to handle the weird writebatch iterator callbacks. I've added a trait and the caller implements that to receive the writebatch put/delete callbacks. However, my lack of talent for properly handling the reference-to-pointer-to-reference conversion is causing a sigsegv when I run the test. If you look at this commit:

https://github.com/nlfiedler/rust-rocksdb/commit/f67b5ac559c7b499c5979e9b47cf1d3bb341f916

At db.rs:1722 is where I've added a WriteBatch.iterate() and attempted to wrap the trait argument in a boxed pointer to get it through the C API and back again to line 1689. As indicated in the comments, it crashes badly on the call to `put`. Granted, I could forego the trait approach and force the application to use the same C-like state/functions argument approach that `SliceTransform` uses internally, but that's not very Rust-like.

Any guidance would be much appreciated. Thanks.

**Comment by vitvakatu** [comment]
It seems like you're doing slightly inappropriate things with converting to/from Box.

I managed to fix execution, but the test still fails (I do not have enough time right now to fully understand the reason). See the patch:

```patch
Index: src/db.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/db.rs	(revision f67b5ac559c7b499c5979e9b47cf1d3bb341f916)
+++ src/db.rs	(date 1568829961000)
@@ -1686,7 +1686,7 @@
     // let boxed_cb = Box::from_raw(state as *mut &mut dyn WriteBatchIterator);
     // let cb = Box::leak(boxed_cb);
     //
-    let cb = &mut *(state as *mut &mut dyn WriteBatchIterator);
+    let state: Box<&mut dyn WriteBatchIterator> = Box::from_raw(state as *mut &mut dyn WriteBatchIterator);
     //
     // let cb = state as *mut &mut dyn WriteBatchIterator;
     //
@@ -1699,7 +1699,7 @@
     //
     // (*(*cb)).put(
     //
-    (*cb).put(
+    (*state).put(
         key.to_vec().into_boxed_slice(),
         value.to_vec().into_boxed_slice(),
     );
@@ -1719,11 +1719,10 @@
 
 impl WriteBatch {
     // TODO: document this weird callback-based "iterator"
-    pub fn iterate<T>(&self, callbacks: &T)
-    where
-        T: WriteBatchIterator,
+    pub fn iterate(&self, callbacks: &mut dyn WriteBatchIterator)
     {
-        let state = Box::into_raw(Box::new(callbacks));
+        let callbacks: Box<&mut dyn WriteBatchIterator> = Box::new(callbacks);
+        let state = Box::into_raw(callbacks);
         unsafe {
             ffi::rocksdb_writebatch_iterate(
                 self.inner,
@@ -1731,7 +1730,6 @@
                 Some(writebatch_put_callback),
                 Some(writebatch_delete_callback),
             );
-            Box::from_raw(state);
         }
     }
 
Index: tests/test_db.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tests/test_db.rs	(revision f67b5ac559c7b499c5979e9b47cf1d3bb341f916)
+++ tests/test_db.rs	(date 1568829988000)
@@ -281,16 +281,16 @@
         assert!(result.is_ok());
         let mut iter = result.unwrap();
         // verify that 3 batches of 1 put each were done
-        let counts = OperationCounts { puts: 0, deletes: 0 };
+        let mut counts = OperationCounts { puts: 0, deletes: 0 };
         let (seq, batch) = iter.next().unwrap();
         assert_eq!(seq, 2);
-        batch.iterate(&counts);
+        batch.iterate(&mut counts);
         let (seq, batch) = iter.next().unwrap();
         assert_eq!(seq, 3);
-        batch.iterate(&counts);
+        batch.iterate(&mut counts);
         let (seq, batch) = iter.next().unwrap();
         assert_eq!(seq, 4);
-        batch.iterate(&counts);
+        batch.iterate(&mut counts);
         assert!(iter.next().is_none());
         assert_eq!(counts.puts, 3);
         assert_eq!(counts.deletes, 0);
@@ -302,11 +302,11 @@
         let _ = db.write(batch);
         let result = db.get_updates_since(seq2);
         assert!(result.is_ok());
-        let counts = OperationCounts { puts: 0, deletes: 0 };
+        let mut counts = OperationCounts { puts: 0, deletes: 0 };
         // verify that 1 put and 1 delete were done
         let (seq, batch) = iter.next().unwrap();
         assert_eq!(seq, 5);
-        batch.iterate(&counts);
+        batch.iterate(&mut counts);
         assert!(iter.next().is_none());
         assert_eq!(counts.puts, 1);
         assert_eq!(counts.deletes, 1);
```

**Comment by nlfiedler** [comment]
Fixed in commit 6e39fd715be16de157f0858540ae761a48785927

**Comment by tancehao** [comment]
@nlfiedler hello, I created an iterator, and passed its mutable reference to the function iterate(), but the put() and delete() methods are not called, and I don't know why. Could you pleas give me some advises?
`
pub struct WriteBatchIter {
    l: Vec<Message>,
}

impl rocksdb::WriteBatchIterator for WriteBatchIter {
    fn put(&mut self, key: Box<[u8]>, value: Box<[u8]>) {
        info!("put key: {:?}, value: {:?}", key, value);
    }

    fn delete(&mut self, key: Box<[u8]>) {
        info!("delete, key: {:?}", key);
    }
}
` 
![WeChatf92ffc408f8cd998140bda7764a4b057](https://user-images.githubusercontent.com/20390579/133187283-a6abba3b-869d-4e18-91d9-c0059b2b48aa.png)

![WeChat1fa7db7dd352a120d4c2c39c4abd126e](https://user-images.githubusercontent.com/20390579/133187544-1a4bcab9-4c89-4be8-9378-f487248cbbbd.png)

**Comment by aleksuss** [comment]
Maybe because a length of the `wb` is 1 ? 🤔

**Comment by tancehao** [comment]
> What are operations you did with your db before iterate ? Take a look [here](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/tests/test_db.rs#L416).

nothing except calling the function put_cf()

**Comment by nlfiedler** [comment]
@tancehao Sorry for the delay in my response. I don't know what's going wrong, but if you have a full example then I can take a look and see if I can figure out anything.
