### ISSUE TITLE
DBVector and DBPinnableSlice's Send/Sync

### ISSUE THREAD

**Issue by nbdd0121** [rust-rocksdb/rust-rocksdb#336]
I'm using rust-rocksdb in async environment so it involves potentially moving DBVector and DBPinnableSlice between multiple threads, and I noticed that both of them are automatically `!Send` and `!Sync` due to usage of raw pointer. This is overly restrictive.

Both of them are definitely `Sync` as they just points to a chunk of immutable memory.

DBVector is just a thin wrapper around a buffer allocated in C and is freed by `libc::free`, so it is indeed `Send`. I haven't concluded whether DBPinnableSlice is `Send` as I don't quite understand how it destructor interacts with multi-threading, but it probably is `Send` as well.

**Comment by vitvakatu** [comment]
Thank you for creating an issue. We will check if it's possible soon. Do you want to create a PR?

**Comment by nbdd0121** [comment]
I'm okay with creating a PR, it'll pretty much be adding a few lines that re-use the justification of #318. But i couldn't assert the `Send`ability of DBPinnableSlice.
