### ISSUE TITLE
Release 0.13.0

### ISSUE THREAD

**Issue by aleksuss** [rust-rocksdb/rust-rocksdb#348]
@iSynaptic @vitvakatu what do you think about to create a release 0.13 ? Any concerns ?

**Comment by vitvakatu** [comment]
No really blockers I think.

**Comment by iSynaptic** [comment]
I have no objection, but we should confirm that it works with the latest stable, `1.39.0`, which was released today.

**Comment by garious** [comment]
1.39.0 worked for me on HEAD, but not on v0.12.4.

**Comment by aleksuss** [comment]
@garious I've released a patch version of `librocksdb-sys`. It should be ok now. But don't forget to run `cargo update` before rebuild.

**Comment by aleksuss** [comment]
PR for release #351
