### ISSUE TITLE
Lacking lifetime on iterator_cf(_opt)

### ISSUE THREAD

**Issue by ailisp** [rust-rocksdb/rust-rocksdb#356]
DB.iterator_cf and DB.iterator_cf_opt lacks a similar lifetime definition like iterator_opt/iterator_opt:
```
    pub fn iterator<'a, 'b: 'a>(&'a self, mode: IteratorMode) -> DBIterator<'b> {
```
Lack of this make you unable to write a function that takes a &DB and return a DBIterator

**Comment by nearmax** [comment]
Actually, I think it does not make sense for `'b` to have a larger scope than `'a` and `iterator_cg` and `iterator_cf_opt` should be redone. The iterator should not outlive the object it is iterating over (the database). What am I missing?
