### ISSUE TITLE
RocksDB dependencies upgrade to 6.4.6

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [rust-rocksdb/rust-rocksdb#359]
Hi!

I upgrade the rocksdb version from [facebook/rocksdb@76a56d89a](https://github.com/facebook/rocksdb/commit/76a56d89a7740f8dbb01edabf1ea5abc95a67657) to [facebook/rocksdb@e3169e3ea8](https://github.com/facebook/rocksdb/commit/e3169e3ea8762d2f34880742106858a23c8dc8b7).

I have a branch [here](https://github.com/FlorentinDUBOIS/rust-rocksdb/tree/feat/rocksdb/6.4.6) with the modification.

How could I test if the modification do not break anything?

Thanks!

**Comment by vitvakatu** [comment]
Hello.

You can create a PR and our Travis will do the testing part.
