### ISSUE TITLE
Allow setting atomic_flush option

### ISSUE THREAD

**Issue by mappum** [rust-rocksdb/rust-rocksdb#378]
There is currently no way to set `atomic_flush`, and it defaults to 0. This is an important setting that my application depends on for consistency.

**Comment by mappum** [comment]
Note that RocksDB doesn't currently add a `rocksdb_options_set_atomic_flush` method so the bindings don't have a way to set this option yet.

**Comment by mappum** [comment]
I opened a PR on RocksDB: https://github.com/facebook/rocksdb/pull/6307

Until then, could it make sense to change the RocksDB submodule to target my fork, or possibly merge my changes into a `rust-rocksdb/rocksdb` fork?

**Comment by vitvakatu** [comment]
Thank you implementing this feature!

> Until then, could it make sense to change the RocksDB submodule to target my fork, or possibly merge my changes into a rust-rocksdb/rocksdb fork?

I don't think we should do it until new facebook/rocksdb version released. For your projects, I suggest to use [overriding dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#overriding-dependencies).

**Comment by aleksuss** [comment]
@mappum could you please describe your case which, in your opinion, requires this option ? 

> Note that it is not necessary to set atomic_flush to true if WAL is always enabled since WAL allows the database to be restored to the last persistent state in WAL.

The quote from [here](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L1088).

**Comment by mappum** [comment]
@aleksuss The WAL is always disabled in my application, since all the operations are already persisted via Tendermint BFT consensus. In the event of a machine crash that loses writes, Tendermint would just replay the previous transactions and my RocksDB store would deterministically rebuild the lost writes. Disabling the WAL gives a significant performance increase.

Although, this use case isn't common to most users of this library.
