### ISSUE TITLE
Please ship the changes since 0.13.0

### ISSUE THREAD

**Issue by mvines** [rust-rocksdb/rust-rocksdb#401]
There are some nice features that have landed in the master branch since 0.13.0 was shipped.  Would it be possible see a 0.13.1 or 0.14.0 on crates.io soon?   Thanks!

**Comment by aleksuss** [comment]
Yeah. I plan to publish a new release in the near future.

**Comment by mvines** [comment]
@aleksuss - when can I expect a new release?  Thanks!

**Comment by dvdplm** [comment]
Let me know if I can do anything to help! :)

**Comment by aleksuss** [comment]
I plan to publish 0.14 release after merge #402.

**Comment by ordian** [comment]
@aleksuss now that #402 is merged, is it blocked on adding tests in #406?

**Comment by aleksuss** [comment]
@ordian exactly. I want to add the feature from #406 as well. It seems to be useful and extends the public API. Let's wait a little.

**Comment by mvines** [comment]
A more rapid release model would be nice.  `cargo publish` is pretty quick.

**Comment by dvdplm** [comment]
> A more rapid release model would be nice. `cargo publish` is pretty quick.

Not sure if it's intentional or not but your comment sounds impolite. Please let's be respectful of the maintainers here and remember that we paid them $0 for their work.

**Comment by aleksuss** [comment]
Done with #408

**Comment by mvines** [comment]
Thanks for shipping 0.14.0 @aleksuss. My previous comment was absolutely not intended to be impolite.  I'm very grateful for this project and appreciate their efforts.   Thank you.
