### ISSUE TITLE
ColumnFamily is Send but not Sync

### ISSUE THREAD

**Issue by winstonewert** [rust-rocksdb/rust-rocksdb#407]
ColumnFamily is marked as Send but not Sync. But since I can only get a reference to ColumnFamily this doesn't seem useful. Rather it seems that it should be Sync.

**Comment by aleksuss** [comment]
Could you please describe a case when you really need it ? It seems to be `Send` is unnecessary now.

**Comment by winstonewert** [comment]
Basically, I was trying to do something like:

```
let cf = db.cf_handle("thing");

thingies.par_iter().map(|x| db.get_cf(&cf)).collect();

```

The map closure needs to be Sync because it will run in parallel in many threads. But I can't do this because the cf isn't Sync.

**Comment by vitvakatu** [comment]
Makes sense to me, RocksDB must manage multithreading access in this case.

**Comment by timokoesters** [comment]
I need this to be Sync too. Is there a better workaround than wrapping it in a Mutex? (I guess I could re-fetch the handle every time, but that's probably more inefficient)

**Comment by mjgarton** [comment]
Did anyone find a workaround for this?

**Comment by winstonewert** [comment]
As I recall, I worked around it by putting my ColumnFamily in a struct that did `unsafe impl Sync for X` on.

**Comment by rklaehn** [comment]
We also need this. We have a case where we use a RocksDB in an Arc in a code base that relies on async. Currently we have to get the cf handles on every operation, which is both ugly and expensive.

If cf handle was Sync we could grab them on startup to avoid having to get them all the time.

Currently the workaround is to just declare the holder of the cf handles as sync, but we would prefer not to do that....

```
unsafe impl Sync for CfHandles<'_> {}
```

**Comment by zaidoon1** [comment]
any update on this? It would be great if we can avoid having to get the cf handler all the time before writing to the cf. Similar to rklaehn, I want to grab the cf handles at startup and then just use it.

**Comment by Chaoses-Ib** [comment]
I'm wondering why `ColumnFamily` and `BoundColumnFamily` are not marked `Sync` since RocksDB is thread-safe. The `UnboundColumnFamily` is marked `Send + Sync`, and `BoundColumnFamily` is a `UnboundColumnFamily` whose lifetime is bound to DB. Then why does bounding lifetime wound make it `!Sync`?

**Comment by jhpratt** [comment]
I've opened a PR to implement this for the reason stated above: #915.
