### ISSUE TITLE
MergeFn that returns &[u8] and reduce copy?

### ISSUE THREAD

**Issue by xuchen-plus** [rust-rocksdb/rust-rocksdb#410]
In my case, I need to merge values with flatbuffers builder, which returns &[u8] that refers to inner object of the builder.
In order to pass this &[u8] to rocksdb, I have to copy it to a new Vec<[u8]>, which will be copied again in the full_merge_callback, and will be copied once more by rocksdb itself.
In this case, the buffer would be **copied 3 times**.
It would be better to allow MergeFn return just &[u8], and because rocksdb would immediately copy it into its memtable in an synchrounous way, the memory should be safe, IMHO.

**Comment by vitvakatu** [comment]
Hello

> and because rocksdb would immediately copy it into its memtable in an synchrounous way, the memory should be safe, IMHO.

I don't think it is true. @aleksuss looks like UB, huh?

**Comment by xuchen-plus** [comment]
> 
> 
> Hello
> 
> > and because rocksdb would immediately copy it into its memtable in an synchrounous way, the memory should be safe, IMHO.
> 
> I don't think it is true. @aleksuss looks like UB, huh?

Hi, thanks for your reply. Based on my reading on the rocksdb's C API impl ([https://github.com/facebook/rocksdb/blob/master/db/c.cc#L370](url)), the returned raw buffer will be copied into the MergeOperationOutput::new_value field (which is a std::string) immediately.
