### ISSUE TITLE
ReadOptions::fill_cache is not public?

### ISSUE THREAD

**Issue by xuchen-plus** [rust-rocksdb/rust-rocksdb#414]
`fn fill_cache(&mut self, v: bool);`
Any chance that this can be a pub fn?

**Comment by vitvakatu** [comment]
Hello

I think it should be possible. Care to submit a PR? This function probably needs documentation and some unit tests (if possible).

**Comment by xuchen-plus** [comment]
> 
> 
> Hello
> 
> I think it should be possible. Care to submit a PR? This function probably needs documentation and some unit tests (if possible).

Sure. I'll submt a PR later.

**Comment by xuchen-plus** [comment]
I see this has been addressed in #442 so close it.
