### ISSUE TITLE
An error when linking librocksdb.a 

### ISSUE THREAD

**Issue by Andy320** [rust-rocksdb/rust-rocksdb#418]
OS: ubuntu18.04
llvm: 9
gcc: 7.5
musl: installed by "apt-get install musl-dev musl-tools"

Actually I made a docker image with llvm added into based on rust-musl-builder :
https://github.com/emk/rust-musl-builder/blob/master/Dockerfile

when building my rust code which depends on rust-rocksdb in the above docker, 
the static lib was created under the directory 
"target/x86_64-unknown-linux-musl/release/build/librocksdb-sys-5fbe87372b39bfff/out/lib"

But finally I got a link error:

`error: linking with `cc` failed: exit code: 1`
...
...
  `= note: /usr/bin/ld: /home/rust/src/target/x86_64-unknown-linux-musl/release/deps/liblibrocksdb_sys-d27d70d68c6a426b.rlib(version_set.o): undefined reference to symbol '__printf_chk@@GLIBC_2.3.4'
          //lib/x86_64-linux-gnu/libc.so.6: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status`

in cargo.toml:
`[dependencies.rocksdb]`
`version = "0.14.0"`
`default-features = false`
`features = ["lz4"]`

in rust code:
`let db: rocksdb::DB = rocksdb::DB::open_default(path).expect("can not open rocksdb");`

By the way, everything works fine on my mac book.

So can you please give me some suggestions? 
Thanks a lot.

**Comment by Andy320** [comment]
I search the key words and find a similiar issue about another rust project. 
Paste it here, not sure is it helpful?

[https://github.com/rust-bio/rust-htslib/issues/80](url)

**Comment by vitvakatu** [comment]
Hello

Did you try to disable all features, including `lz4`? I experienced some issues with this feature enabled on Linux.

**Comment by Andy320** [comment]
@vitvakatu 
In release mode , librocksdb.a is created but linking error. I tried it in debug mode again, and failed to build the librocksdb.a before the linking. The error is like somehow "undefined reference to symbol '[another one]@@GLIBC_2.3.[3](not 2.3.4)'".
So now I am not sure whether rocksdb-sys supports musl libc, i.e. rustup target: x86_64-unknown-linux-musl 
Now I am compiling llvm10 using gcc9.3 in a centos7 docker, and will try it again using glibc, i.e. target: x86_64-unknown-linux-gnu
If so, rocksdb-sys can not be used in environment with only musl libs supported like alpine, am I understanding right? thanks

**Comment by Andy320** [comment]
[ubuntu18.04/llvm10(downloaded binary)/x86_64-unknown-linux-gnu] ==>ok
[centos7/llvm10(compiled with gcc9.1)/x86_64-unknown-linux-gnu] ==> ok
[Darwin19.3/llvm9(packaged)/x86_64-apple-darwin] ==> ok
[ubuntu18.04/llvm10(downloaded binary)/x86_64-unknown-linux-musl] ==> failed

close this issue.

thanks all
