### ISSUE TITLE
Rocksdb Fails to Register Merge Operators

### ISSUE THREAD

**Issue by jparr721** [rust-rocksdb/rust-rocksdb#426]
Rocksdb fails to register merge operators when using the `open_cf` function. For some reason, when creating with the following minimal example, using a column family makes the code completely ignore the `set_merge_operator` options.
```rust
use rocksdb::{ColumnFamilyDescriptor, MergeOperands, Options, DB};

fn test_provided_merge(
    _: &[u8],
    existing_val: Option<&[u8]>,
    operands: &mut MergeOperands,
) -> Option<Vec<u8>> {
    let nops = operands.size_hint().0;
    let mut result: Vec<u8> = Vec::with_capacity(nops);
    if let Some(v) = existing_val {
        for e in v {
            result.push(*e);
        }
    }
    for op in operands {
        for e in op {
            result.push(*e);
        }
    }
    Some(result)
}

int main () {
    let mut opts = Options::default();
    opts.set_merge_operator("test operator", test_provided_merge, None);
    opts.create_if_missing(true);
    opts.create_missing_column_families(true);
    match DB::open_cf(&opts, "temp", &["cf1"]) {
        Ok(_db) => println!("successfully opened db with column family"),
        Err(e) => panic!("failed to open db with column family: {}", e),
    }
    Ok(())
}
```
Looking into the `OPTIONS` files, we can observe the following:
```
[CFOptions "default"]
  sample_for_compression=0
  compaction_pri=kMinOverlappingRatio
  merge_operator=nullptr
  compaction_filter_factory=nullptr

[CFOptions "cf1"]
  sample_for_compression=0
  compaction_pri=kMinOverlappingRatio
  merge_operator=nullptr
  compaction_filter_factory=nullptr
```

It appears that both merge operators and compaction filters are being completely ignored for both the default column family context as well as my custom one here.

I looked into the function and was surprised to see all of the `open_*` variant functions call the `open_cf` routine. It appears that something must be overriding _some_ of my options and keeping others. It appears maybe that the use of `default` option objects appears to be disregarding the user-defined options objects. 

Not sure what the root cause here is, though. If this is an intended function for rocksdb, is there a workaround I can take advantage of to make my column families at startup?

Thanks
-J

**Comment by jparr721** [comment]
I have found a workaround in the following form:
```rust
use rocksdb::{ColumnFamilyDescriptor, MergeOperands, Options, DB};

fn test_provided_merge(
    _: &[u8],
    existing_val: Option<&[u8]>,
    operands: &mut MergeOperands,
) -> Option<Vec<u8>> {
    let nops = operands.size_hint().0;
    let mut result: Vec<u8> = Vec::with_capacity(nops);
    if let Some(v) = existing_val {
        for e in v {
            result.push(*e);
        }
    }
    for op in operands {
        for e in op {
            result.push(*e);
        }
    }
    Some(result)
}

int main () {
    let mut opts = Options::default();
    opts.set_merge_operator("test operator", test_provided_merge, None);
    opts.create_if_missing(true);
    opts.create_missing_column_families(true);
    let cfs =  vec!["cf1"];
    let db = DB::open(&opts, "temp").unwrap();
    for cf in cfs.into_iter() {
        db.create_cf(cf, &opts).unwrap();
    }
    Ok(())
}
```
This has solved the problem of options objects being overridden.

**Comment by jparr721** [comment]
Turns out this only works on creation, when reopening the database this fails as the column families to do not get reopened.

**Comment by aleksuss** [comment]
Hello. It's because `open_cf` method creates and uses default options for column families under the hood. Take a look here #370

**Comment by jparr721** [comment]
@aleksuss Thank you, I seem to have missed that. Would you mind if I open a documentation PR? Looks like others have accidentally fallen into this trap.

**Comment by aleksuss** [comment]
> Would you mind if I open a documentation PR? 

Yes. Sure.
