### ISSUE TITLE
Expose CancelAllBackgroundWork

### ISSUE THREAD

**Issue by ailisp** [rust-rocksdb/rust-rocksdb#427]
It's mentioned in rocksdb wiki to speed up time to waiting:

> Q: Is it safe to close RocksDB while another thread is issuing read, write or manual compaction requests?
A: No. The users of RocksDB need to make sure all functions have finished before they close RocksDB. You can speed up the waiting by calling CancelAllBackgroundWork().

It'd be great to have it exposed in rust-rocksdb

**Comment by DarkEld3r** [comment]
It is definitely a good idea, but currently this function isn't exposed in the C API. I have made a pull request (https://github.com/facebook/rocksdb/pull/6832), but it will take some time for it to be merged and a new version to be released.
