### ISSUE TITLE
include/rocksdb/env.h

### ISSUE THREAD

**Issue by zach-schoenberger** [rust-rocksdb/rust-rocksdb#434]
Hi, not sure if this is the proper place for this, but I was wondering if there was any plan to start support for the env.h configs? I ask because I'm looking to use the conifg described here https://github.com/facebook/rocksdb/wiki/Thread-Pool to change the SetBackgroundThreads.

**Comment by aleksuss** [comment]
Hello. As far as I can see C API provides all needed stuff to realise this on the Rust side. So I suppose it would be done in the near future. By the way feel free to create PR if you want 🙂

**Comment by zach-schoenberger** [comment]
Cool, I had thought about doing that. I just wanted to make sure there wasn't something already in motion or if i missed something since the bindings were already there.

**Comment by stanislav-tkach** [comment]
I guess this can be closed after #448 is merged.

**Comment by stanislav-tkach** [comment]
Closed in #448.
