### ISSUE TITLE
Issues with Cache

### ISSUE THREAD

**Issue by NeoLegends** [rust-rocksdb/rust-rocksdb#462]
Hey, we've been updating to v0.15. We were using https://docs.rs/rocksdb/0.15.0/rocksdb/struct.BlockBasedOptions.html#method.set_lru_cache before, but since that is deprecated we are refactoring. We noticed two main issues:

- The dependency of `DB` on the lifetime of the `Cache` is not encoded in the type system. As far as I understand the documentation, dropping the Cache before dropping the DB results in undefined behavior. Perhaps this could be safeguarded by either making `Cache` refcounted or by using lifetimes.
- `Cache` is not `Send` because it contains a raw pointer. I'm not sure if that's desired behavior. The implementation of `set_lru_cache` (https://docs.rs/rocksdb/0.15.0/src/rocksdb/db_options.rs.html#419-426) suggests `Send`ness is not required.

**Comment by tim-patterson** [comment]
Just a note to say as far the lifetimes, I've noticed the same thing when setting custom env's (ie the in-mem one for testing).
(it segfaults if the env doesn't live long enough).

Maybe there's more places where this is going to be an issue.

I had a quick look but to me it looks like current API isn't really going play nice with rusts lifetime tracking?

**Comment by stanislav-tkach** [comment]
There are definitely some issues with lifetimes and I think this should be improved. Unfortunately, it would be a breaking change. Ideally I think that we should finish #431 and fix lifetime issues along with (or after) that.

**Comment by NeoLegends** [comment]
I don't think this being a breaking change matters, being that this library is still marked as unstable (i. e. major version 0). This could actually pose a soundness vulnerability, since failing to manage the cache properly and thus causing UB is possible without `unsafe`.

**Comment by stanislav-tkach** [comment]
I agree that the breaking change is much less important than the correct api. I mean that if we are going to change the api anyway, then ideally it can be done once.

**Comment by acrrd** [comment]
When opening a database with `open_cf_descriptors` each `ColumnFamilyDescriptor` has an `Options` that could have an `Env` and `Cache`, do we have to keep track of those?
