### ISSUE TITLE
Question: Why do create_cf() and drop_cf() require mutability? 

### ISSUE THREAD

**Issue by jrobhoward** [rust-rocksdb/rust-rocksdb#468]
**Question:**
Sometime between 0.12.0 and 0.13.0, the interface changed so `create_cf() `and `drop_cf()` now require a mutable reference to self instead of an immutable reference.
- Was this done because of an underlying issue with RocksDB itself (e.g. it's the only safe way to create or drop column families)?
- Or was this done for a reason specific to the Rust bindings?

**Background (why I ask):**
I would like the ability to create and remove column families dynamically (at runtime, after the DB instance has been opened) from an arc-wrapped DB.  Wrapping it in rwlock (instead of arc) works fine to accomplish this.
- ...but I would also like to perform iteration over a column family (which borrows from DB) --and I cannot find a way to iterate without holding the rwlock.

Thanks-

**Comment by stanislav-tkach** [comment]
This was changed in the https://github.com/rust-rocksdb/rust-rocksdb/commit/54ff3db8ecd93770dfa73ea864d713a283c3ce21 commit (https://github.com/rust-rocksdb/rust-rocksdb/pull/314 pull request). As far as I can see, this was done to remove internal `RwLock`. The pull request has some motivation description, but perhaps @aleksuss can add more details.

**Comment by aleksuss** [comment]
Yeah. @stanislav-tkach is right. The main reason is to remove internal `RwLock` which could decrease a performance.

**Comment by jrobhoward** [comment]
Thanks for the prompt responses.  Now that I understand why a mutable reference is used in `create_cf()` and `drop_cf()`, I have a couple options available and can move forward:

- Originally, I was planning on using a Cargo/Crates.io [patch](https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html) to revert the code and go back to immutable methods (e.g. use the original code or conditionally enable it with an optional Cargo feature flag).
- Since my original post, I think I may have found a way to do this without patching the rust-rocksdb crate:  I can try wrapping the DB in an rwlock (instead of arc) and using `IntoIter` with another (intermediate) struct (see [link1](https://www.reddit.com/r/rust/comments/7l97u0/iterator_struct_of_an_iterable_inside_a_lock_from/) & [link2](https://play.rust-lang.org/?gist=083f85cd6e564b4c9abda0dbf3a33010&version=stable) for additional info).  Assuming it works, this should suit my needs (i.e. I need the ability to iterate and dynamically add|remove column families, but my application doesn't have the highest throughput or concurrency requirements).

Thanks again-
