### ISSUE TITLE
 Compiling librocksdb-sys v6.11.4 failed on macOS 10.15.7

### ISSUE THREAD

**Issue by yiyanwannian** [rust-rocksdb/rust-rocksdb#474]
err:
  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/XXX/dev/src/github.com/rust-rocksdb/rust-rocksdb/librocksdb-sys/target/release/build/librocksdb-sys-a6c8953761ec2b75/out/rocksdb/cache/cache.o" "-c" "rocksdb/cache/cache.cc" with args "c++" did not execute successfully (status code exit code: 1).

detail error info below err.txt
[err.txt](https://github.com/rust-rocksdb/rust-rocksdb/files/5511110/err.txt)

**Comment by kaimast** [comment]
I am also getting build errors on two different linux machines. One with Ubuntu 20.10 and one with ubuntu 20.04. Both have the most recent rust nightly...

Is there a specific version of clang or GCC that should be used?

**Comment by rohitjoshi** [comment]
This issue came when I ran `cargo update` which updated `cc` package. I manually changed back to `v1.0.61` version and it works fine now.

**Comment by Maher4Ever** [comment]
@rohitjoshi How did you downgrade the `cc` build dependency?

**Comment by yiyanwannian** [comment]
after add build-dependencies.cc toCargo.toml, but some error still over there
![image](https://user-images.githubusercontent.com/8225547/99672786-dc156d80-2aae-11eb-8ae9-b92edbdbb424.png)

**Comment by yiyanwannian** [comment]
My issue still on my macos
rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/xxx/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.48.0 (7eac88abb 2020-11-16)

**Comment by yiyanwannian** [comment]
fixed by change /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath file 
line: 304 
change include <math.h> to include "math.h"

**Comment by juancolchete** [comment]
I was using linux on WSL2 but, this was one of the first posts related with my problem that I found and I will leave one link and I hope help someone that is also stucked when build librocksdb-sys v6.11.4 [full solution](https://stackoverflow.com/questions/66583720/some-error-failed-to-run-custom-build-command-for-librocksdb-sys-v6-11-4/76791499#76791499)

resumed solution:
sudo apt-get update
sudo apt-get install g++
