### ISSUE TITLE
DB::multi_get()

### ISSUE THREAD

**Issue by JEnoch** [rust-rocksdb/rust-rocksdb#485]
Hi,
I see that `rocksdb_multi_get()` is available and tested in librocksdb_sys. But it's not exposed via the Rust API.
Is there a plan to add a `DB::multi_get()` operation any time soon ?

**Comment by stanislav-tkach** [comment]
I will try to finish the #487 pull request which adds these functions soon.

**Comment by JEnoch** [comment]
That's great! Thanks!
