### ISSUE TITLE
merge operator delete_callback 

### ISSUE THREAD

**Issue by zhangsoledad** [rust-rocksdb/rust-rocksdb#494]
I got a case that needs to use `merge` function.
I notice https://github.com/rust-rocksdb/rust-rocksdb/pull/457 introduce `delete_callback` to handle memory release and avoid copy.
https://github.com/xuchen-plus/rust-rocksdb/blob/392d20a4df6c9319822eaabfd517c7697a735377/src/db_options.rs#L945-L952
```rust
            let mo = ffi::rocksdb_mergeoperator_create(
                mem::transmute(cb),
                Some(merge_operator::destructor_callback),
                Some(full_merge_callback),
                Some(partial_merge_callback),
                Some(merge_operator::delete_callback),
                Some(merge_operator::name_callback),
            );
```

But https://github.com/rust-rocksdb/rust-rocksdb/pull/481  overwrite it back.

https://github.com/BoOTheFurious/rust-rocksdb/blob/9881373ed920727523e5c1cb714a2680ba97c1e2/src/db_options.rs#L944-L950

https://github.com/BoOTheFurious/rust-rocksdb/blob/9881373ed920727523e5c1cb714a2680ba97c1e2/src/db_options.rs#L971-L975

```
           let mo = ffi::rocksdb_mergeoperator_create(
                Box::into_raw(cb) as _,
                Some(merge_operator::destructor_callback::<F, F>),
                Some(full_merge_callback::<F, F>),
                Some(partial_merge_callback::<F, F>),
                None,
                Some(merge_operator::name_callback::<F, F>),
            );
```

So my question: Is this mistake? Or this is on purpose？

**Comment by stanislav-tkach** [comment]
Honestly, I have missed that detail in the #481 pull request. Would you like to submit a pull request to fix that issue?
