### ISSUE TITLE
Is operand merge expected behaviour?

### ISSUE THREAD

**Issue by markusgod** [rust-rocksdb/rust-rocksdb#507]
Exmaple: https://github.com/markusgod/rocksdb-test

I was trying to add some 'update' logic to merge operator, but my idea that operands are previously recorded commands (see commented code main.rs:45) are wrong.

**Comment by akrylysov** [comment]
Could you please add more details? What output are you expecting to see?

**Comment by markusgod** [comment]
I was confused that rocksdb returned "merged bytes" and separate values ([98][97, 98, 97, 98]).
