### ISSUE TITLE
Unicode path names issue on Windows reappeared

### ISSUE THREAD

**Issue by rajivshah3** [rust-rocksdb/rust-rocksdb#512]
It seems like the `ROCKSDB_WINDOWS_UTF8_FILENAMES` flag was removed in https://github.com/rust-rocksdb/rust-rocksdb/pull/493. This flag fixed #85 and allowed paths with non-ANSI characters. Would it be possible to re-add it, or was there a specific reason it was removed?

**Comment by aleksuss** [comment]
Yes. Sure.
