### ISSUE TITLE
Please support using existing Rust library crates for zstd, zlib, etc

### ISSUE THREAD

**Issue by joshtriplett** [rust-rocksdb/rust-rocksdb#514]
The rocksdb crate only seems to support vendoring zstd/zlib/etc, which means if a Rust crate depends on rocksdb and also pulls in zstd/zlib/etc, it'll end up with symbol conflicts between the rocksdb vendored zstd/zlib/etc and the other version they include.

Please consider using crates like `zstd-sys` and `libz-sys` rather than vendoring. Those crates do support statically vendoring the library, and also support not doing so, giving the user of rocksdb control over how they want to use zstd/zlib/etc.

**Comment by stanislav-tkach** [comment]
It is a great idea, perhaps you would like to submit a pull request? I think it makes sense to start with replacing one of these dependencies.

**Comment by arthurprs** [comment]
Definetly needed. Right now it's not possible to compile rdkafka with rust-rocksdb if lz4 feature is enabled in the latter. The TIKV fork uses the "compression crate" approach https://github.com/tikv/rust-rocksdb/tree/master/librocksdb_sys
