### ISSUE TITLE
Please expose the compression option "parallel_threads".

### ISSUE THREAD

**Issue by joshtriplett** [rust-rocksdb/rust-rocksdb#515]
RocksDB supports parallel compression, which provides a significant performance improvement for zstd. Please consider exposing the `parallel_threads` compression option.

**Comment by stanislav-tkach** [comment]
As far as I can see, this option isn't available through C API. I have made the [pull request](https://github.com/facebook/rocksdb/pull/8302).

**Comment by stanislav-tkach** [comment]
The pull request is merged, but we need to wait for a release that includes these changes.

**Comment by teor2345** [comment]
Just wondering if this has made it into the Rust API yet?

I had a look for `parallel_threads`, but I couldn't find it.
