### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by McFranko** [rust-rocksdb/rust-rocksdb#516]
I can't find any documentation for this crate. It would be helpful if there was a docs.rs link or something, if there is inline documentation, then it shouldn't be to hard to generate docs with `cargo doc`, unless I'm missing something

**Comment by mappum** [comment]
There is a link at the top of the README, the docs are available at
https://docs.rs/rocksdb.

**Comment by McFranko** [comment]
Oh, my bad, sorry
