### ISSUE TITLE
Public ThreadMode trait

### ISSUE THREAD

**Issue by YjyJeff** [rust-rocksdb/rust-rocksdb#532]
I want to write a function that accepts both DBWithThreadMode\<MultiThreaded\> and DBWithThreadMode\<SingleThreaded\> as parameter. However, because of ThreadMode trait is private, I can not do it.  Any idea about how to achieve it? I think make the ThreadMode trait public can solve this problem.

**Comment by TsumiNa** [comment]
Exactly the same question.

**Comment by substack** [comment]
This would also help to reuse code that might sometimes need to operate on a snapshot. I'm using macros to duplicate the code because this trait isn't public.

**Comment by aleksuss** [comment]
@ryoqun, could you add this request in PR #509 ?

**Comment by ryoqun** [comment]
sorry radio silence... I'll work on #509 and try to piggybuck this nice feedback there too, hopefully this weekend. :)

**Comment by ryoqun** [comment]
also, this is also done: https://github.com/rust-rocksdb/rust-rocksdb/pull/509/files#r664163946
