### ISSUE TITLE
Load RocksDB option file

### ISSUE THREAD

**Issue by Congyuwang** [rust-rocksdb/rust-rocksdb#568]
https://github.com/facebook/rocksdb/blob/main/include/rocksdb/utilities/options_util.h#L73

Is there any way to load DB options from the RocksDB option file?

This allows users to open existing rocksDB without configuring the compatible options manually.

**Comment by akrylysov** [comment]
rust-rocksdb uses [C RocksDB API](https://github.com/facebook/rocksdb/blob/dc5de45af8fc1bcc90edea5cd9a5695bd85a8baf/include/rocksdb/c.h). It doesn't seem the C API provides a way to load options from a file. To add this feature to rust-rocksdb you'll need to extend the C RocksDB API first.

**Comment by akrylysov** [comment]
I took another look at the C API and noticed there is [rocksdb_get_options_from_string](https://github.com/facebook/rocksdb/blob/2a67d475f1a3fe24b4baae6e590cecabca099464/db/c.cc#L4791), it might be close to what you are looking for.

**Comment by Congyuwang** [comment]
Yes close to. It uses such a format as string input to get options: [StringToMap](https://github.com/facebook/rocksdb/blob/dc5de45af8fc1bcc90edea5cd9a5695bd85a8baf/options/options_helper.cc#L560)
```
  // Example:
  //   opts_str = "write_buffer_size=1024;max_write_buffer_number=2;"
  //              "nested_opt={opt1=1;opt2=2};max_bytes_for_level_base=100"
```
in the implementation of [GetDBOptionsFromString](https://github.com/facebook/rocksdb/blob/dc5de45af8fc1bcc90edea5cd9a5695bd85a8baf/options/options_helper.cc#L748).

whereas the automatically dumped `OPTIONS-0000x` file looks like:
```
[DBOptions]
  max_background_flushes=-1
  compaction_readahead_size=0
  strict_bytes_per_sync=false
  wal_bytes_per_sync=0
  max_open_files=-1
...
[TableOptions/PlainTable "default"]
  store_index_in_file=false
  full_scan_mode=false
  encoding_type=kPlain
  hash_table_ratio=0.750000
```
The more convenient [LoadLatestOptions](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/utilities/options_util.h#L73) however is not exposed as C API.

**Comment by Congyuwang** [comment]
https://github.com/facebook/rocksdb/issues/9233

**Comment by Congyuwang** [comment]
I've drafted a PR, which seems to work as long as RocksDB version >= v7.5.3. However, got some cargo clippy and strange compiling issue 'disk space not enough' on GitHub action. #701

**Comment by Congyuwang** [comment]
Can any one take a look at PR #724?
