### ISSUE TITLE
Update to rocksdb 6.26.1

### ISSUE THREAD

**Issue by mfachalforte** [rust-rocksdb/rust-rocksdb#571]
We had some issue with rocksdb where reads on the secondary fail to see recent updates from the primary. This was fixed in [v6.25.0](https://github.com/facebook/rocksdb/releases/tag/v6.25.1). It'd be nice to have this update on the package.

**Comment by niklasf** [comment]
Done in v0.18.0.

**Comment by tv42** [comment]
I believe this can be closed now, librocksdb-sys is at version 0.11.0+8.1.1 so RocksDB v8.1.1
