### ISSUE TITLE
Support Write Buffer Manager

### ISSUE THREAD

**Issue by timokoesters** [rust-rocksdb/rust-rocksdb#587]
https://github.com/facebook/rocksdb/wiki/Write-Buffer-Manager

It would be great if you could add support for the write buffer manager. This would allow me to do this:
> Limit the total memtable usage across multiple column families and DBs under a threshold

**Comment by girlbossceo** [comment]
Does https://github.com/rust-rocksdb/rust-rocksdb/pull/850 solve this issue?

**Comment by zaidoon1** [comment]
yes, https://github.com/rust-rocksdb/rust-rocksdb/pull/850 solves this issue
