### ISSUE TITLE
Does the upgrade affect my tests?

### ISSUE THREAD

**Issue by akiradeveloper** [rust-rocksdb/rust-rocksdb#605]
Today, I found my regression test (in docker container) is failing because creation of the rocksdb store fails. Here is my repository https://github.com/akiradeveloper/lol and I use rocksdb as one of the backend.

The master branch was surely ok on Thrusday but not ok Saturday today. I also confirmed that former branches also started to fail today.

From what I see this code fails.

```rust
    pub fn create(&self) {
        let mut db_opts = Options::default();
        db_opts.create_if_missing(true);
        db_opts.create_missing_column_families(true);
        let mut opts = Options::default();
        opts.set_comparator(CMP, comparator_fn);
        let cf_descs = vec![
            ColumnFamilyDescriptor::new(CF_ENTRIES, opts),
            ColumnFamilyDescriptor::new(CF_TAGS, Options::default()),
            ColumnFamilyDescriptor::new(CF_CTRL, Options::default()),
        ];
        let db = DB::open_cf_descriptors(&db_opts, &self.path, cf_descs).unwrap();

        let initial_ballot = Ballot {
            cur_term: 0,
            voted_for: None,
        };
        let cf = db.cf_handle(CF_CTRL).unwrap();
        let b: Vec<u8> = initial_ballot.into();
        db.put_cf(&cf, BALLOT, b).unwrap();
    }
```

From the commit, this repository switched to rocksdb 6.28.2 two days ago. Do you think anything affects my tests?

**Comment by aleksuss** [comment]
It's weird because there is a [6.20.3](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/Cargo.toml#L34) version of `librcoskdb-sys` is used in the master branch. You can find out which one `librocksdb-sys` is used looking in your `Cargo.lock` file.

**Comment by akiradeveloper** [comment]
Yes. It is weird.

I see the Cargo.lock and it is 6.20.3.

Because I am not confident that this is caused by rocksdb I will close this issue. Thanks you. I will find the other issue.

I hope newer version will come soon.
