### ISSUE TITLE
librocksdb_sys::bz_internal_error conflicts with bzip2-sys::bz_internal_error

### ISSUE THREAD

**Issue by nikurt** [rust-rocksdb/rust-rocksdb#609]
I'm getting the following link error due to the duplicate symbol when linking a binary with link-time optimizations:
```
   Compiling neard v0.0.0 (/home/nikurt/nearcore-rdb-3/neard)
warning: Linking globals named 'bz_internal_error': symbol multiply defined!

error: failed to load bc of "librocksdb_sys-33c86cdce183a558.librocksdb_sys.8e9e6b3e-cgu.0.rcgu.o":

warning: `neard` (bin "neard") generated 1 warning
error: could not compile `neard` due to previous error; 1 warning emitted
make: *** [Makefile:34: neard-release] Error 101
```

Symbols are defined here:
* `librocksdb-sys`: https://github.com/rust-rocksdb/rust-rocksdb/blob/180e65e1b00f6b032e1513d94a4f0a4de7cafba1/librocksdb-sys/src/lib.rs#L32
* `bzip2-sys`: https://github.com/alexcrichton/bzip2-rs/blob/016e18155ef7c05983ea244cae1344c5b68defd8/bzip2-sys/lib.rs#L73

A workaround is to disable feature `bzip2` of crate `rocksdb`.

Link-time optimizations defined in my [`Makefile`](https://github.com/near/nearcore/blob/5568df666a0f5025c724027814069050acb194c6/Makefile#L2) as follows:
```
CARGO_PROFILE_RELEASE_LTO = fat
```

**Comment by dnrusakov** [comment]
Is it possible to release a new version of the `rocksdb` crate in order to accommodate this change? The current version available on crates.io is 0.18.0 and doesn't have all recent changes including this one. cc @aleksuss
