### ISSUE TITLE
How to fetch and update in `rocksdb`

### ISSUE THREAD

**Issue by pvdrz** [rust-rocksdb/rust-rocksdb#619]
This is a question rather than an actual issue report but I was wondering what would be the atomic way of doing a fetch and update operation like `fn update(db: rocksdb::DB, key: Key, f: impl Fn(Option<Value>) -> Option<Value>)` where a value is retrieved from a column family using `key` and then updated using `f`.

I know that merge operators let you define operations like this but not in a dynamic way (merge operators are set in `Options` before opening the database and cannot be modified while the db is running iiuc).

Thank you :)

**Comment by redbaron** [comment]
As a workaround, static merge operator can branch dynamically based on value or existing value
