### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by neelsomani** [rust-rocksdb/rust-rocksdb#629]
Hey folks, I'm trying to compile a package (Solana) that has rocksdb as a dependency. I tried doing `cargo build` on both my Mac and in a Docker container (ubuntu:20.04). This is the error I'm getting:

```
#11 4094.7    Compiling rocksdb v0.15.0
#11 4096.5 error: an inner attribute is not permitted in this context
#11 4096.5    --> ledger/src/sigverify_shreds.rs:249:13
#11 4096.5     |
#11 4096.5 249 |             #![allow(clippy::cast_ptr_alignment)]
#11 4096.5     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#11 4096.5     |
#11 4096.5     = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files
#11 4096.5     = note: outer attributes, like `#[test]`, annotate the item following them
```

What should I do? Thank you!

**Comment by aleksuss** [comment]
Hello. A compiler says that the problem is here `ledger/src/sigverify_shreds.rs:249:13`. I think that's your code, isn't it?

**Comment by neelsomani** [comment]
Hmm possibly another dependency of the Solana build..let me re-run and circle back

**Comment by neelsomani** [comment]
My mistake, yeah it's another project giving me issues
