### ISSUE TITLE
When will be the next release?

### ISSUE THREAD

**Issue by MarcErdmann** [rust-rocksdb/rust-rocksdb#634]
Now that support for BlobDB is merged, is there a release planned anytime soon? Thanks.

**Comment by remram44** [comment]
Fortunately Cargo makes it easy to use crates from Git. It would help to have it in docs.rs and such though.

**Comment by Voxelot** [comment]
> Fortunately Cargo makes it easy to use crates from Git. It would help to have it in docs.rs and such though.

This isn't a real answer if you need your crate to be publishable.
