### ISSUE TITLE
Failing to build Rust RocksDb on CentOS 7.5

### ISSUE THREAD

**Issue by eaglecoth** [rust-rocksdb/rust-rocksdb#638]
I am trying to compile Rust RocksDB on CentOS 7.5.  I am unsure of how to debug this further -- Any suggestions as to how I could continue resolving this?  What would be the best way to continue debugging?

**Relevant dependencies and versions:**
-  gcc                 x86_64     8.5.0-4.el8_5               appstream      23 M
-  gcc-c++             x86_64     8.5.0-4.el8_5               appstream      12 M
-  make                x86_64     1:4.2.1-10.el8              baseos        498 k
- Installing dependencies:
-  annobin             x86_64     9.72-1.el8_5.2              appstream     111 k
-  cpp                 x86_64     8.5.0-4.el8_5               appstream      10 M
-  glibc-devel         x86_64     2.28-164.el8                baseos        1.0 M
-  glibc-headers       x86_64     2.28-164.el8                baseos        480 k
-  isl                 x86_64     0.16.1-6.el8                appstream     841 k
-  kernel-headers      x86_64     4.18.0-348.7.1.el8_5        baseos        8.3 M
-  libmpc              x86_64     1.1.0-9.1.el8               appstream      61 k
-  libstdc++-devel     x86_64     8.5.0-4.el8_5               appstream     2.0 M
-  libxcrypt-devel     x86_64     4.1.1-6.el8                 baseos         25 k
- ` llvm        x86_64   12.0.1-2.module_el8.5.0+918+ed335b90    appstream    16 M
-  llvm-libs   x86_64   12.0.1-2.module_el8.5.0+918+ed335b90    appstream    23 M
-  llvm-toolset
-  clang                       x86_64  12.0.1-4.module_el8.5.0+1025+93159d6c appstream   82 k
-  clang-libs                  x86_64  12.0.1-4.module_el8.5.0+1025+93159d6c appstream   22 M
-  clang-resource-filesystem   x86_64  12.0.1-4.module_el8.5.0+1025+93159d6c appstream   14 k
-  compiler-rt                 x86_64  12.0.1-1.module_el8.5.0+892+54d791e1  appstream  3.8 M
-  libomp                      x86_64  12.0.1-1.module_el8.5.0+892+54d791e1  appstream  343 k
-  libomp-devel                x86_64  12.0.1-1.module_el8.5.0+892+54d791e1  appstream   24 k
-  cmake                       x86_64    3.20.2-4.el8          appstream     12 M
-  openssl-devel               x86_64    1:1.1.1k-5.el8_5      baseos       2.3 M
-  protobuf-compiler           x86_64    3.5.0-13.el8          appstream    789 k
-  systemd-devel               x86_64    239-51.el8_5.2        baseos       387 k
-  yum-utils                   noarch    4.0.21-3.el8          baseos        73 k
-  zlib-devel                  x86_64    1.2.11-17.el8         baseos        58 k
- Installing dependencies:
-  cmake-data                  noarch    3.20.2-4.el8          appstream    1.7 M
-  cmake-filesystem            x86_64    3.20.2-4.el8          appstream     44 k
-  cmake-rpm-macros            noarch    3.20.2-4.el8          appstream     44 k
-  dbus-glib                   x86_64    0.110-2.el8           baseos       127 k
-  dnf-plugins-core            noarch    4.0.21-3.el8          baseos        70 k
-  keyutils-libs-devel         x86_64    1.5.10-9.el8          baseos        48 k
-  krb5-devel                  x86_64    1.18.2-14.el8         baseos       560 k
-  libcom_err-devel            x86_64    1.45.6-2.el8          baseos        38 k
-  libkadm5                    x86_64    1.18.2-14.el8         baseos       187 k
-  libselinux-devel            x86_64    2.9-5.el8             baseos       200 k
-  libsepol-devel              x86_64    2.9-3.el8             baseos        87 k
-  libuv                       x86_64    1:1.41.1-1.el8_4      appstream    156 k
-  libverto-devel              x86_64    0.3.0-5.el8           baseos        18 k
-  pcre2-devel                 x86_64    10.32-2.el8           baseos       605 k
-  pcre2-utf16                 x86_64    10.32-2.el8           baseos       229 k
-  pcre2-utf32                 x86_64    10.32-2.el8           baseos       220 k
-  protobuf                    x86_64    3.5.0-13.el8          appstream    892 k
-  python3-dateutil            noarch    1:2.6.1-6.el8         baseos       251 k
-  python3-dbus                x86_64    1.2.4-15.el8          baseos       134 k
-  python3-dnf-plugins-core    noarch    4.0.21-3.el8          baseos       234 k
-  python3-six                 noarch    1.11.0-8.el8          baseos        38 k
-  vim-filesystem              noarch    2:8.0.1763-16.el8     appstream     49 k
- 

**Error:**

warning: c++: fatal error: Killed signal terminated program cc1plus
warning: compilation terminated.
error: failed to run custom build command for `librocksdb-sys v0.6.1+6.28.2`
...
error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "lz4/lib/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-DLZ4=1" "-DNDEBUG=1" "-DOS_LINUX" "-DROCKSDB_PLATFORM_POSIX" "-DROCKSDB_LIB_IO_POSIX" "-DROCKSDB_SUPPORT_THREAD_LOCAL" "-o" "/opt/atlassian/pipelines/agent/build/solana/target/debug/build/librocksdb-sys-67bcbf4f7b8b5ba9/out/rocksdb/db/db_impl/db_impl.o" "-c" "rocksdb/db/db_impl/db_impl.cc" with args "c++" did not execute successfully (status code exit status: 1).

**Comment by mjm918** [comment]
I faced the same issue on Centos7. Run the following commands, it will solve your issue

```
sudo yum -y install llvm-3.9-dev libclang-3.9-dev clang-3.9
sudo yum install llvm-toolset-7
scl enable llvm-toolset-7 bash
```
