### ISSUE TITLE
Corruption: Corrupted compressed block contents: Snappy

### ISSUE THREAD

**Issue by mjm918** [rust-rocksdb/rust-rocksdb#644]
Hi Team,
First of all thank you for your great work on RocksDb.

We are using rocksdb as underlying storage engine for our search engine. Everything works great!

However, we noticed an issue,
`Corruption: Corrupted compressed block contents: Snappy`

It happens when we kill our program with `Crtl+C` and then try to start again. Rocksdb fails to start as database is corrupted and the `repair` function doesn't work in this case.

I tried to google it and found that it comes from leveldb. And this error should occur only if we use Snappy compression. But in our program we are not using any compression.

We are using the following options:

```
let mut opts = Options::default();
opts.create_if_missing(true);
opts.create_missing_column_families(true);
opts.increase_parallelism(4);
opts.set_max_open_files(-1);
opts.set_compression_type(DBCompressionType::None);
opts.set_error_if_exists(false);
opts.set_max_file_opening_threads(-1);
opts.set_allow_concurrent_memtable_write(true);
opts.set_allow_mmap_writes(true);
opts.set_allow_mmap_reads(true);
```

How can we avoid the corruption issue? Is there anything that we missed?

Please suggest.
Thank you

**Comment by abyss-w** [comment]
Hello, I also encountered the same problem in use, have you found a solution?

**Comment by mjm918** [comment]
So far no luck. I searched online and found few posts like [this](https://groups.google.com/g/leveldb/c/YvszWNio2-Q) and [this](https://github.com/wbolster/plyvel/issues/137) but so far no luck.

I'm using mac for development and this problem doesnt happen on mac. when i move to production which is running on centos, i encounter this issue

**Comment by mjm918** [comment]
I found something in the documentation:

> `set_use_fsync` If true, then every store to stable storage will issue a fsync. If false, then every store to stable storage will issue a fdatasync. This parameter should be set to true while storing data to filesystem like ext3 that can lose files after a reboot.

Since my server is using ext3 file system, it could be the issue.
