### ISSUE TITLE
How to set_stats_level?

### ISSUE THREAD

**Issue by power1628** [rust-rocksdb/rust-rocksdb#663]
Native Rocksdb has the ability to set statistics level ([set_stats_level](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/statistics.h#L685)).
It's very useful for debugging performance issues.
It would be good if rust-rocksdb can do this like rocksdb.

**Comment by 4TT1L4** [comment]
I think is already possible using the set_statistics_level function of the Options.

There is an example in the test_db.rs:

https://github.com/rust-rocksdb/rust-rocksdb/blob/b8f79d937cb9dcac3a897119bc5f10bbd4f3f589/tests/test_db.rs#L388

Make sure to explicitly enable statistics as well.

**Comment by power1628** [comment]
@4TT1L4 you're right, this is fixed by #853, thanks for the information.
