### ISSUE TITLE
Support using existing Rust library crates for LZ4

### ISSUE THREAD

**Issue by JoshLind** [rust-rocksdb/rust-rocksdb#666]
Hi, I'm running into a similar issue that was discussed here (https://github.com/rust-rocksdb/rust-rocksdb/issues/514) and partially fixed here (https://github.com/rust-rocksdb/rust-rocksdb/pull/555). Specifically, we have a project that relies on the LZ4 compression crate (https://crates.io/crates/lz4) as well as rocksdb (with the "lz4" feature enabled). When the project is built in some environments, we get multiple definitions errors, e.g.,:

```
= note: .../target/debug/deps/liblz4_sys-f40b00295671b3fc.rlib(lz4hc.o): in function `LZ4_sizeofStateHC':
          /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lz4-sys-1.9.3/liblz4/lib/lz4hc.c:882: multiple definition of `LZ4_sizeofStateHC'; .../target/debug/deps/liblibrocksdb_sys-bb115f55214b8b62.rlib(lz4hc.o):/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-6.20.3/lz4/lib/lz4hc.c:570: first defined here
          /usr/bin/ld: .../target/debug/deps/liblz4_sys-f40b00295671b3fc.rlib(lz4hc.o): in function `LZ4_freeStreamHC':
          /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lz4-sys-1.9.3/liblz4/lib/lz4hc.c:960: multiple definition of `LZ4_freeStreamHC'; ..//target/debug/deps/liblibrocksdb_sys-bb115f55214b8b62.rlib(lz4hc.o):/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-6.20.3/lz4/lib/lz4hc.c:615: first defined here
```

The partial-fix PR says (https://github.com/rust-rocksdb/rust-rocksdb/pull/555):

> This does not use snappy-sys or lz4-sys because neither currently exposes the include directory (via "cargo:include=..", which we can use as "DEP_XXX_INCLUDE") to dependencies when building a vendored version of the library, which we need.

Is this still true today?

Thanks for the help! 😄

**Comment by msmouse** [comment]
Issue has been fixed. Thanks @niklasf
