### ISSUE TITLE
Compaction filter not called when using merge operators

### ISSUE THREAD

**Issue by mdecimus** [rust-rocksdb/rust-rocksdb#672]
Hi,

Not sure if this is a RocksDB limitation but I have a column family with the following options:

```
let mut cf_opts = Options::default();
cf_opts.set_merge_operator_associative("merge", fnc_merge);
cf_opts.set_compaction_filter("compact", fnc_compact);
```

Let's say that `fnc_merge` adds/subtracts `i32` operands while `fnc_compact` deletes the key if the value reaches `0`.

The compaction filter works perfectly when I call `put_cf` followed by `merge_cf`:

```
db.put_cf(&handle, "test", 1).unwrap();
db.merge_cf(&handle, "test", -1).unwrap();
db.compact_range_cf(&handle, None::<&[u8]>, None::<&[u8]>);
```

However, if I use `merge_cf` to set the first value, the compaction filter is never called:

```
db.merge_cf(&handle, "test", 1).unwrap();
db.merge_cf(&handle, "test", -1).unwrap();
db.compact_range_cf(&handle, None::<&[u8]>, None::<&[u8]>);
```

Thank you for your help and maintaining this library.

**Comment by kidcooky** [comment]
> our h

wonder did you figure out why? i think even without the merge operator, i encounter similar thing. @mdecimus

**Comment by mdecimus** [comment]
Compaction is done automatically by RocksDB at some point. Manual compaction however still does not work.

**Comment by kidcooky** [comment]
> ounter si

yeah, i submitted an issue here: https://github.com/rust-rocksdb/rust-rocksdb/issues/877, i don't think it's a merge operator issue since i didn't use it but still encountered?
