### ISSUE TITLE
Unsupport type '__uint128_t' when I used arm-linux-gnueabihf

### ISSUE THREAD

**Issue by Dirreke** [rust-rocksdb/rust-rocksdb#681]
When I cross-compile it by the compiler "arm-linux-gnueabihf", it reported that '__uint128_t' was not declared in this scope

```
The following warnings were emitted during compilation:

warning: In file included from rocksdb/util/hash.h:26:0,
warning:                  from rocksdb/cache/cache_key.cc:13:
warning: rocksdb/util/fastrange.h: 在静态成员函数‘static Range rocksdb::detail::FastRangeGenericImpl<long long unsigned int, Range>::Fn(uint64_t, Range)’中:
warning: rocksdb/util/fastrange.h:62:5: 错误： ‘__uint128_t’在此作用域中尚未声明
warning:      __uint128_t wide = __uint128_t{range} * hash;
warning:      ^~~~~~~~~~~
warning: rocksdb/util/fastrange.h:62:5: 附注： suggested alternative: ‘__uint32_t’
warning:      __uint128_t wide = __uint128_t{range} * hash;
warning:      ^~~~~~~~~~~
warning:      __uint32_t
warning: rocksdb/util/fastrange.h:62:45: 错误： 一元 ‘*’参数类型无效(有‘uint64_t {aka long long unsigned int}’)
warning:      __uint128_t wide = __uint128_t{range} * hash;
warning:                                              ^~~~
warning: rocksdb/util/fastrange.h:63:31: 错误： ‘wide’在此作用域中尚未声明
warning:      return static_cast<Range>(wide >> 64);
warning:                                ^~~~
warning: rocksdb/util/fastrange.h:63:31: 附注： suggested alternative: ‘fwide’
warning:      return static_cast<Range>(wide >> 64);
warning:                                ^~~~
warning:                                fwide

error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4
```

#620 Add `config.define("HAVE_UINT128_EXTENSION", Some("1"));` to the [build.rs](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/librocksdb-sys/build.rs#L236). It can cause problem.

In fact, not all compilers support the type of int128, so the [facebook/rocksdb#7338](https://github.com/facebook/rocksdb/pull/7338)  uses makefile to check int128 compatibility. The type of int128 is not related to target, but related to compiler。

So I think [ `config.define("HAVE_UINT128_EXTENSION", Some("1"));` ](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/librocksdb-sys/build.rs#L236) should be deleted.
@niklasf

**Comment by JEnoch** [comment]
Hi!
I'm also facing this issue after bumping to `rocksdb = "0.19.0"`.
Any plan to merge #682 and release it soon ?
