### ISSUE TITLE
`key_may_exist` does not return key-value pair when key exist

### ISSUE THREAD

**Issue by curtainp** [rust-rocksdb/rust-rocksdb#715]
Hi,
 I need to determine if the key exists and return the associated value when the key exists, but I realized that the existing implementation only determines the existence, is there any plan to implement this at the moment, I am happy to implement this feature.

**Comment by aleksuss** [comment]
Could you explain what wrong with `get`, `get_cf` methods?

**Comment by curtainp** [comment]
No error, except that i noticed that the `key_may_exist` interface can return the relevant values together when the key exists, avoiding the need to call `get` or `get_cf` later.

**Comment by aleksuss** [comment]
Sorry but I don't get it. What's the problem to do this:
```rust
match db.get(b"key") {
    Ok(Some(value) => { // key exists, use the value },
    Ok(None) => { // key doesn't exist, no value },
    Err(e) => eprintln!("error occurred {e}"),
} 
```
?
