### ISSUE TITLE
Compaction Decision::Change leaks memory

### ISSUE THREAD

**Issue by niklasf** [rust-rocksdb/rust-rocksdb#729]
`Box::into_raw(newval.into_boxed_slice()) as *mut c_char` introduced in 5ed104348817faf899309aba79473d751febbbbe via #725 leaks memory.  The `'static` bound was required, because RocksDB does not yet offer a mechanism to free newly allocated values after using them: https://github.com/facebook/rocksdb/issues/6624 / https://github.com/facebook/rocksdb/pull/9771.

**Comment by aleksuss** [comment]
@niklasf, nice catch. Could you propose any solution to this?

**Comment by niklasf** [comment]
I don't see a good way without an upstream change/addition like facebook/rocksdb#9771 :(

**Comment by aleksuss** [comment]
The commit was reverted. So there is no memory leak for now.
