### ISSUE TITLE
Windows Build not working

### ISSUE THREAD

**Issue by DasLixou** [rust-rocksdb/rust-rocksdb#805]
So I am trying to use this library because of dependency of surrealdb. It needs to build via Clang. Note: I'm on Windows. 
I came across an issue where it couldnt find the libclang.dll in a special env lib so I searched it up and added it. 
It then said: 
```
   Compiling librocksdb-sys v0.10.0+7.9.2
error: failed to run custom build command for `librocksdb-sys v0.10.0+7.9.2`

Caused by:
  process didn't exit successfully: `C:\Users\lixou\Projects\SurrealProject\target\debug\build\librocksdb-sys-e0c5cfd0cd2a1aed\build-script-build` (exit code: 101)
  --- stderr
  rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found
  thread 'main' panicked at 'unable to generate rocksdb bindings: ClangDiagnostic("rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found\n")', C:\Users\lixou\.cargo\registry\src\index.crates.io-6f17d22bba15001f\librocksdb-sys-0.10.0+7.9.2\build.rs:40:10
```
So I tried to add the include things from Clang to PATH env variable, where I could also find a `stdarg.h`, which is the error. But even after a reboot and new terminal an everything, I get the compiler error from above. 
Has anyone else achieved to get this compiling on Windows? How can I get it running?

Thanks :)

**Comment by axnsan12** [comment]
For me it works by just doing `set LIBCLANG_PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin` - Llvm/Clang tools installed via VS installer

**Comment by DasLixou** [comment]
> For me it works by just doing `set LIBCLANG_PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin` - Llvm/Clang tools installed via VS installer

That was the first issue that i got fixed. but now the problem is that it can't find `stdarg.h` even if i have `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\lib\clang\15.0.1\include` in PATH

**Comment by DasLixou** [comment]
Got it working by setting `LIBRARY_PATH` to the include folder and restarting

**Comment by HangShuYH** [comment]
Hi there, I encountered a similar problem.
`.\zstd/lib/zstd.h:16:10: fatal error: 'stddef.h' file not found`
I have setting the LIBRARY_PATH and LIBCLANG_PATH.
