### ISSUE TITLE
Request to be added as a maintainer

### ISSUE THREAD

**Issue by zaidoon1** [rust-rocksdb/rust-rocksdb#846]
Hi, I'm actively using this repo for critical projects and would like to help with maintaining it per  https://github.com/rust-rocksdb/rust-rocksdb/blob/master/MAINTAINERSHIP.md. Mainly reviewing prs, to speed up the release process.

@stanislav-tkach @aleksuss hopefully that's ok with you!

**Comment by aleksuss** [comment]
We appreciate any contribution. Thanks.

**Comment by stanislav-tkach** [comment]
To be honest, I don't have enough time to properly participate in the `rust-rocksdb` maintenance, so I would be glad to see more people involved.

**Comment by zaidoon1** [comment]
that sounds great! I don't know what the next step is but I'm interested in proceeding to become an official maintainer

**Comment by aleksuss** [comment]
@zaidoon1 I will ask the repo's owner to add you as a maintainer.
