### ISSUE TITLE
Way to ensure checkpoint is completed?

### ISSUE THREAD

**Issue by kidcooky** [rust-rocksdb/rust-rocksdb#888]
Hey, I have a periodic job to create checkpoint to a local directory, and serve this checkpoint to other machine with another thread, I wonder what I can do to ensure the checkpoint is successfully done and all data is checkpointed before sending it out? i.e. How do I know the checkpoint has been fully done to file system so I can compress and send it out?
```
fn create_and_save_checkpoint(db: Arc<DB>, snapshot_dir: &Path) -> Result<(), error::Error> {
    if snapshot_dir.exists() {
        fs::remove_dir_all(snapshot_dir)?;
    }
    let checkpoint = Checkpoint::new(&db)?;
    checkpoint.create_checkpoint(snapshot_dir)?;
    Ok(())
}
```

**Comment by zaidoon1** [comment]
checkpoint creation is a blocking call so once `  checkpoint.create_checkpoint(snapshot_dir)?; ` returns, the checkpoint would have already be completed/done
