### ISSUE TITLE
Properties for TransactionDB

### ISSUE THREAD

**Issue by David548219** [rust-rocksdb/rust-rocksdb#899]
Allow getting property (https://docs.rs/rocksdb/latest/rocksdb/properties/index.html) values from rust code for TransactionDB (If accessible via c++ api). At the moment `property_value` methods are only available for DBCommon.

**Comment by 4TT1L4** [comment]
I have created a pull request with the suggested changes:
- https://github.com/rust-rocksdb/rust-rocksdb/pull/902

**Comment by 4TT1L4** [comment]
Now this should be possible with the change from my PR:
- https://github.com/rust-rocksdb/rust-rocksdb/pull/902

See the test code for examples:

https://github.com/rust-rocksdb/rust-rocksdb/blob/5f704745599f0561a4262c27536edc354395aba8/tests/test_transaction_db_property.rs#L37

And for int properties:

https://github.com/rust-rocksdb/rust-rocksdb/blob/5f704745599f0561a4262c27536edc354395aba8/tests/test_transaction_db_property.rs#L58

**Comment by David548219** [comment]
Thanks for quick resolution, awaiting cargo release with new feature
