### ISSUE TITLE
User-defined timestamp (#901) is both bad design and bugged

### ISSUE THREAD

**Issue by larry0x** [rust-rocksdb/rust-rocksdb#904]
Two problems with #901:

1. It doesn't work because of a bug
2. It's bad design

## The bug

Here is an incredibly simple reproduction of the bug: https://github.com/rust-rocksdb/rust-rocksdb/compare/master...left-curve:rust-rocksdb:bug

```bash
$ cargo test --test test_timestamp 
    Finished test [unoptimized + debuginfo] target(s) in 0.04s
     Running tests/test_timestamp.rs (target/debug/deps/test_timestamp-b0e3ef20cfc17ed6)

running 1 test
test timestamping_works ... FAILED

failures:

---- timestamping_works stdout ----
thread 'timestamping_works' panicked at 'assertion failed: `(left == right)`
  left: `"sardine"`,
 right: `"tuna"`', tests/test_timestamp.rs:32:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    timestamping_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--test test_timestamp`
```

The cause of this is a memory bug in `ReadOption::set_timestamp`:

```rust
pub fn set_timestamp<S: AsRef<[u8]>>(&mut self, ts: S) {
    let ts = ts.as_ref();
    unsafe {
        ffi::rocksdb_readoptions_set_timestamp(
            self.inner,
            ts.as_ptr() as *const c_char,
            ts.len() as size_t,
        );
    }
}
```

Here we pass the pointer `ts.as_ptr()` to the FFI. However, this pointer only lives as long as `ts`, which may be dropped before we perform the `db.get_opt`.

The solution to this, is to have `ReadOptions` own the timestamp value. This ensures the timestamp lives as long as the `ReadOptions`:

```diff
pub struct ReadOptions {
    pub(crate) inner: *mut ffi::rocksdb_readoptions_t,
+   timestamp: Option<Vec<u8>>,
    iterate_upper_bound: Option<Vec<u8>>,
    iterate_lower_bound: Option<Vec<u8>>,
}

impl ReadOptions {
    pub fn set_timestamp<S: AsRef<[u8]>>(&mut self, ts: S) {
-       let ts = ts.as_ref();
+       let ts = ts.as_ref().to_owned();
        unsafe {
            ffi::rocksdb_readoptions_set_timestamp(
                self.inner,
                ts.as_ptr() as *const c_char,
                ts.len() as size_t,
            );
        }
+       self.timestamp = Some(ts);
    }
}
```

This btw is the same reason why `ReadOptions` also owns `iterate_{upper,lower}_bound` values.

With this, the test passes:

```plain
Finished test [unoptimized + debuginfo] target(s) in 0.04s
     Running tests/test_timestamp.rs (target/debug/deps/test_timestamp-b0e3ef20cfc17ed6)

running 1 test
test timestamping_works ... ok

successes:

successes:
    timestamping_works

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

I don't know how the tests in the PR managed to pass. Maybe just luck.

## The bad design

This implementation "enshrines" big endian `u64` as the timestamp. What if I want to use a different size (like `u128`), or use little endian? In fact, RocksDB's own [built-in comparator](https://github.com/facebook/rocksdb/blob/main/util/comparator.cc#L299-L300) uses little endian.

Please take a look at our implementation: https://github.com/rust-rocksdb/rust-rocksdb/compare/v0.21.0...left-curve:rust-rocksdb:v0.21.0-grug. Happy to do another PR to fix the bug, or better, just revert #901 and accept ours.

**Comment by zaidoon1** [comment]
@larry0x can you make a pr that reverts the 901 and adds your version and we can review that.

**Comment by larry0x** [comment]
> @larry0x can you make a pr that reverts the 901 and adds your version and we can review that.

Thanks @zaidoon1, please see #905.

Instead of reverting #901, I chose to keep it and apply fixes.
