### ISSUE TITLE
zero copy multi_get

### ISSUE THREAD

**Issue by MathGeniusJodie** [rust-rocksdb/rust-rocksdb#907]
so I have my own fork with multi_get that returns an iterator over &[u8] to avoid copying into a vec and it's a bit faster and uses less memory on larger values, would it be possible to add a multi_get_raw or something?

**Comment by zaidoon1** [comment]
are you asking to update this repo to have a zero copy multi_get like your fork? If so, can you create a pr with your changes and we can review it

**Comment by MathGeniusJodie** [comment]
no problem

**Comment by MathGeniusJodie** [comment]
oh, I see you've already implemented it as batched_multi_get_cf

**Comment by MathGeniusJodie** [comment]
feel free to close this if you don't want to make a batched_multi_get for convenience
