### ISSUE TITLE
Unable to Open DB with different TTL per-ColumnFamily

### ISSUE THREAD

**Issue by jszwec** [rust-rocksdb/rust-rocksdb#958]
Hi,

I'm trying to open a database with different TTLs for each ColumnFamily. However, it seems like the current Rust API signature for [open_cf_descriptors_with_ttl](https://docs.rs/rocksdb/latest/rocksdb/struct.DBCommon.html#method.open_cf_descriptors_with_ttl) only accepts a single TTL.

Looking at the [C++ implementation](https://github.com/facebook/rocksdb/blob/b339d089ed4a7ac7a8ed4ab7d57cccdc0602f0ed/utilities/ttl/db_ttl_impl.cc#L354), it seems that it takes a vector, so per-ColumnFamily TTLs should be possible. Is this an oversight in the Rust API, or am I misunderstanding something?

Thanks in advance!
Jacek

**Comment by 0xdeafbeef** [comment]
@aleksuss @stanislav-tkach i think you can close this

**Comment by aleksuss** [comment]
@jszwec if #963 resolves this issue, then close the issue, please.

**Comment by jszwec** [comment]
perfect! thanks!
